const tier = 7;

export const ABYSS_ENEMIES = [
  {
    name: 'Abyssal Wraith',
    element: 'cold',
    image: '/enemies/abyssal-wraith.jpg',
    tier: tier,
    damage: 3,
    coldDamage: 3,
    coldResistance: 30,
    fireResistance: 20,
    airResistance: 10,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 15,
    life: 26,
    armor: 8,
    evasion: 8,
    attackRating: 14,
    gold: 11,
    xp: 13,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
  },
  {
    name: 'Shadowclaw',
    element: 'air',
    image: '/enemies/shadowclaw.jpg',
    tier: tier,
    airDamage: 2,
    evasion: 9,
    airResistance: 20,
    damage: 0,
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 10,
    life: 24,
    armor: 7,
    attackRating: 13,
    gold: 10,
    xp: 12,
    materialDropWeights: {},
    tags: ['abyss', 'shadow'],
  },
  {
    name: 'Hellhound',
    element: 'fire',
    image: '/enemies/hellhound.jpg',
    tier: tier,
    damage: 4,
    fireDamage: 4,
    fireResistance: 25,
    airResistance: 10,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    life: 30,
    armor: 9,
    evasion: 8,
    attackRating: 14,
    gold: 12,
    xp: 13,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
  {
    name: 'Infernal Knight',
    element: 'fire',
    image: '/enemies/infernal-knight.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    damage: 3,
    fireDamage: 4,
    armor: 13,
    fireResistance: 20,
    coldResistance: 5,
    airResistance: 5,
    life: 34,
    attackRating: 16,
    evasion: 7,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    gold: 13,
    xp: 14,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
];
