export const ABYSS_ENEMIES = [
  {
    name: 'Abyssal Wraith',
    element: 'cold',
    image: '/enemies/abyssal-wraith.jpg',
    tier: 7,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
  },
  {
    name: 'Dreadfang',
    element: 'air',
    image: '/enemies/dreadfang.jpg',
    tier: 7,
    materialDropWeights: {},
    tags: ['nightmare', 'beast', 'abyss'],
  },
  {
    name: 'Shadowclaw',
    element: 'air',
    image: '/enemies/shadowclaw.jpg',
    tier: 7,
    materialDropWeights: {},
    tags: ['shadow', 'beast', 'abyss'],
  },
  {
    name: 'Hellhound',
    element: 'fire',
    image: '/enemies/hellhound.jpg',
    tier: 7,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
  {
    name: 'Infernal Knight',
    element: 'fire',
    image: '/enemies/infernal-knight.jpg',
    tier: 7,
    multiplier: {
      materialDrop: 1.1,
    },
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
];
