import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 7;

export const ABYSS_ENEMIES = [
  {
    name: 'Abyssal Wraith',
    element: 'cold',
    image: '/enemies/abyssal-wraith.jpg',
    tier: tier,
    damage: 3 * getEnemyStatMultiplier(tier),
    coldDamage: 3 * getEnemyStatMultiplier(tier),
    coldResistance: 30,
    fireResistance: 20,
    airResistance: 10,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 15,
    life: 26 * getEnemyStatMultiplier(tier),
    armor: 8 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    gold: 11 * getEnemyStatMultiplier(tier),
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
  },
  {
    name: 'Shadowclaw',
    element: 'air',
    image: '/enemies/shadowclaw.jpg',
    tier: tier,
    airDamage: 2 * getEnemyStatMultiplier(tier),
    evasion: 9 * getEnemyStatMultiplier(tier),
    airResistance: 20,
    damage: 0 * getEnemyStatMultiplier(tier),
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 10,
    life: 24 * getEnemyStatMultiplier(tier),
    armor: 7 * getEnemyStatMultiplier(tier),
    attackRating: 13 * getEnemyStatMultiplier(tier),
    gold: 10 * getEnemyStatMultiplier(tier),
    xp: 12 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['abyss', 'shadow'],
  },
  {
    name: 'Hellhound',
    element: 'fire',
    image: '/enemies/hellhound.jpg',
    tier: tier,
    damage: 4 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    fireResistance: 25,
    airResistance: 10,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    life: 30 * getEnemyStatMultiplier(tier),
    armor: 9 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
  {
    name: 'Infernal Knight',
    element: 'fire',
    image: '/enemies/infernal-knight.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    damage: 3 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    armor: 13 * getEnemyStatMultiplier(tier),
    fireResistance: 20,
    coldResistance: 5,
    airResistance: 5,
    life: 34 * getEnemyStatMultiplier(tier),
    attackRating: 16 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    gold: 13 * getEnemyStatMultiplier(tier),
    xp: 14 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
];
