const tier = 7;

export const ABYSS_ENEMIES = [
  {
    name: 'Abyssal Wraith',
    element: 'cold',
    image: '/enemies/abyssal-wraith.jpg',
    tier: tier,
    coldDamage: 3,
    coldResistance: 30,
    fireResistance: 20,
    life: 24,
    damage: 4,
    xp: 12,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
  },
  {
    name: 'Shadowclaw',
    element: 'air',
    image: '/enemies/shadowclaw.jpg',
    tier: tier,
    airDamage: 2,
    evasion: 8,
    airResistance: 20,
    damage: 3,
    coldResistance: 10,
    xp: 11,
    materialDropWeights: {},
    tags: ['abyss', 'shadow'],
  },
  {
    name: 'Hellhound',
    element: 'fire',
    image: '/enemies/hellhound.jpg',
    tier: tier,
    fireDamage: 5,
    fireResistance: 25,
    airResistance: 10,
    life: 28,
    damage: 4,
    armor: 8,
    xp: 12,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
  {
    name: 'Infernal Knight',
    element: 'fire',
    image: '/enemies/infernal-knight.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    fireDamage: 4,
    armor: 12,
    fireResistance: 20,
    life: 32,
    attackRating: 15,
    xp: 13,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: '🔥',
  },
];
