import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 2;

export const CRYSTAL_CAVE_ENEMIES = [
  {
    name: 'Crystal Golem',
    element: 'earth',
    image: '/enemies/crystal-golem.jpg',
    tier: tier,
    life: 32 * getEnemyStatMultiplier(tier),
    armor: 16 * getEnemyStatMultiplier(tier),
    damage: 1 * getEnemyStatMultiplier(tier),
    earthDamage: 3 * getEnemyStatMultiplier(tier),
    earthResistance: 30,
    coldResistance: 10,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    attackRating: 4 * getEnemyStatMultiplier(tier),
    evasion: 3 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9,
    materialDropWeights: {
      crystalized_rock: 4,
    },
    tags: ['golem', 'crystal'],
  },
  {
    name: 'Gem Guardian',
    element: 'earth',
    image: '/enemies/gem-guardian.jpg',
    tier: tier,
    earthResistance: 20,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    armor: 12 * getEnemyStatMultiplier(tier),
    damage: 0,
    earthDamage: 1.5 * getEnemyStatMultiplier(tier),
    waterDamage: 1.5 * getEnemyStatMultiplier(tier),
    evasion: 4 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['guardian', 'gem', 'cave'],
  },
  {
    name: 'Grimspike',
    element: 'earth',
    image: '/enemies/grimspike.jpg',
    tier: tier,
    attackSpeed: 1.2,
    airResistance: 10,
    fireResistance: 5,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    materialDropWeights: {},
    tags: ['spike', 'earth', 'cave'],
  },
  {
    name: 'Shardling',
    element: 'earth',
    image: '/enemies/shardling.jpg',
    tier: tier,
    damage: 1 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    earthResistance: 15,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    attackSpeed: 1.2,
    materialDropWeights: {},
    tags: ['shard', 'earth', 'cave'],
  },
];
