export const CRYSTAL_CAVE_ENEMIES = [
  {
    name: 'Crystal Golem',
    element: 'earth',
    image: '/enemies/crystal-golem.jpg',
    tier: 2,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      crystalized_rock: 4,
    },
    tags: ['golem', 'crystal'],
  },
  {
    name: 'Gem Guardian',
    element: 'earth',
    image: '/enemies/gem-guardian.jpg',
    tier: 2,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['guardian', 'gem', 'cave'],
  },
  {
    name: 'Grimspike',
    element: 'earth',
    image: '/enemies/grimspike.jpg',
    tier: 2,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['spike', 'earth', 'cave'],
  },
  {
    name: 'Shardling',
    element: 'earth',
    image: '/enemies/shardling.jpg',
    tier: 2,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['shard', 'earth', 'cave'],
  },
];
