export const CRYSTAL_CAVE_ENEMIES = [
  {
    name: 'Crystal Golem',
    element: 'earth',
    image: '/enemies/crystal-golem.jpg',
    tier: 2,
    life: 30,
    armor: 15,
    earthDamage: 3,
    earthResistance: 30,
    attackRating: 14,
    xp: 11,
    materialDropWeights: {
      crystalized_rock: 4,
    },
    tags: ['golem', 'crystal'],
  },
  {
    name: 'Gem Guardian',
    element: 'earth',
    image: '/enemies/gem-guardian.jpg',
    tier: 2,
    life: 26,
    earthResistance: 20,
    armor: 12,
    earthDamage: 2,
    evasion: 6,
    xp: 10,
    materialDropWeights: {},
    tags: ['guardian', 'gem', 'cave'],
  },
  {
    name: 'Grimspike',
    element: 'earth',
    image: '/enemies/grimspike.jpg',
    tier: 2,
    damage: 4,
    attackSpeed: 1.2,
    airResistance: 10,
    life: 24,
    earthDamage: 1,
    xp: 9,
    materialDropWeights: {},
    tags: ['spike', 'earth', 'cave'],
  },
  {
    name: 'Shardling',
    element: 'earth',
    image: '/enemies/shardling.jpg',
    tier: 2,
    evasion: 10,
    earthResistance: 15,
    armor: 8,
    life: 22,
    xp: 9,
    materialDropWeights: {},
    tags: ['shard', 'earth', 'cave'],
  },
];
