export const DESERT_ENEMIES = [
  {
    name: 'Dunewraith',
    element: 'earth',
    image: '/enemies/dunewraith.jpg',
    tier: 4,
    materialDropWeights: {},
    tags: ['undead', 'sand'],
  },
  {
    name: 'Sandstalker',
    element: 'earth',
    image: '/enemies/sandstalker.jpg',
    tier: 4,
    materialDropWeights: {},
    tags: ['sand', 'scorpion'],
  },
  {
    name: 'Scorching Salamander',
    element: 'fire',
    image: '/enemies/scorching-salamander.jpg',
    tier: 4,
    materialDropWeights: {},
    tags: ['desert', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Dune Blazer',
    element: 'fire',
    image: '/enemies/dune-blazer.jpg',
    tier: 4,
    materialDropWeights: {},
    tags: ['desert', 'sand'],
    icon: '🔥',
  },
];
