const tier = 4;

export const DESERT_ENEMIES = [
  {
    name: 'Dunewraith',
    element: 'earth',
    image: '/enemies/dunewraith.jpg',
    tier: tier,
    earthDamage: 3,
    earthResistance: 20,
    coldResistance: 15,
    armor: 6,
    evasion: 8,
    xp: 10,
    materialDropWeights: {},
    tags: ['desert', 'undead'],
  },
  {
    name: 'Sandstalker',
    element: 'earth',
    image: '/enemies/sandstalker.jpg',
    tier: tier,
    evasion: 12,
    damage: 3,
    earthDamage: 2,
    attackSpeed: 1.1,
    xp: 9,
    materialDropWeights: {},
    tags: ['desert', 'scorpion'],
  },
  {
    name: 'Scorching Salamander',
    element: 'fire',
    image: '/enemies/scorching-salamander.jpg',
    tier: tier,
    fireDamage: 4,
    fireResistance: 30,
    coldResistance: 20,
    life: 26,
    earthResistance: 5,
    xp: 12,
    materialDropWeights: {},
    tags: ['desert', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Dune Blazer',
    element: 'fire',
    image: '/enemies/dune-blazer.jpg',
    tier: tier,
    fireDamage: 3,
    earthResistance: 10,
    attackSpeed: 1.1,
    coldResistance: 5,
    evasion: 8,
    xp: 10,
    gold: 11,
    materialDropWeights: {},
    tags: ['desert', 'sand'],
    icon: '🔥',
  },
];
