export const DESERT_ENEMIES = [
  {
    name: 'Dunewraith',
    element: 'earth',
    image: '/enemies/dunewraith.jpg',
    tier: 4,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['undead', 'sand'],
  },
  {
    name: 'Sandstalker',
    element: 'earth',
    image: '/enemies/sandstalker.jpg',
    tier: 4,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['sand', 'scorpion'],
  },
  {
    name: 'Scorching Salamander',
    element: 'fire',
    image: '/enemies/scorching-salamander.jpg',
    tier: 4,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['desert', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Dune Blazer',
    element: 'fire',
    image: '/enemies/dune-blazer.jpg',
    tier: 4,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['desert', 'sand'],
    icon: '🔥',
  },
];
