import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 1;

export const FOREST_ENEMIES = [
  {
    name: 'Mossback',
    element: 'earth',
    image: '/enemies/mossback.jpg',
    tier: tier,
    life: 30 * getEnemyStatMultiplier(tier),
    armor: 9 * getEnemyStatMultiplier(tier),
    earthResistance: 40,
    coldResistance: 15,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    damage: 3 * getEnemyStatMultiplier(tier),
    earthDamage: 1 * getEnemyStatMultiplier(tier),
    attackRating: 8 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    attackSpeed: 1,
    gold: 8 * getEnemyStatMultiplier(tier),
    xp: 10 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Thornling',
    element: 'earth',
    image: '/enemies/thornling.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    damage: 3 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    earthResistance: 20,
    coldResistance: 10,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    gold: 10 * getEnemyStatMultiplier(tier),
    attackRating: 11 * getEnemyStatMultiplier(tier),
    life: 28 * getEnemyStatMultiplier(tier),
    armor: 6 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Barkhide',
    element: 'earth',
    image: '/enemies/barkhide.jpg',
    tier: tier,
    multiplier: {
      damage: 0.9,
      materialDrop: 1.1,
    },
    life: 34 * getEnemyStatMultiplier(tier),
    armor: 9 * getEnemyStatMultiplier(tier),
    earthResistance: 15,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    evasion: 7 * getEnemyStatMultiplier(tier),
    damage: 2 * getEnemyStatMultiplier(tier),
    earthDamage: 1 * getEnemyStatMultiplier(tier),
    attackRating: 7 * getEnemyStatMultiplier(tier),
    gold: 9 * getEnemyStatMultiplier(tier),
    xp: 9 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Sylvan Wisp',
    element: 'air',
    image: '/enemies/sylvan-wisp.jpg',
    tier: tier,
    multiplier: {
      life: 0.9,
    },
    life: 24 * getEnemyStatMultiplier(tier),
    damage: 0 * getEnemyStatMultiplier(tier),
    evasion: 12 * getEnemyStatMultiplier(tier),
    airDamage: 3 * getEnemyStatMultiplier(tier),
    airResistance: 25,
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 5,
    waterResistance: 10,
    attackSpeed: 1.2,
    armor: 4 * getEnemyStatMultiplier(tier),
    attackRating: 8 * getEnemyStatMultiplier(tier),
    gold: 10 * getEnemyStatMultiplier(tier),
    xp: 9 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['forest'],
  },
];
