const tier = 1;

export const FOREST_ENEMIES = [
  {
    name: 'Mossback',
    element: 'earth',
    image: '/enemies/mossback.jpg',
    tier: tier,
    life: 28,
    armor: 10,
    earthResistance: 50,
    coldResistance: 10,
    xp: 10,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Thornling',
    element: 'earth',
    image: '/enemies/thornling.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    damage: 3,
    earthDamage: 2,
    earthResistance: 25,
    gold: 10,
    attackRating: 12,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Barkhide',
    element: 'earth',
    image: '/enemies/barkhide.jpg',
    tier: tier,
    multiplier: {
      damage: 0.9,
      materialDrop: 1.1,
    },
    life: 32,
    armor: 8,
    earthResistance: 15,
    evasion: 8,
    xp: 9,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Sylvan Wisp',
    element: 'air',
    image: '/enemies/sylvan-wisp.jpg',
    tier: tier,
    multiplier: {
      life: 0.9,
    },
    evasion: 12,
    airDamage: 2,
    airResistance: 25,
    attackSpeed: 1.2,
    gold: 10,
    materialDropWeights: {},
    tags: ['forest'],
  },
];
