const tier = 1;

export const FOREST_ENEMIES = [
  {
    name: 'Mossback',
    element: 'earth',
    image: '/enemies/mossback.jpg',
    tier: tier,
    life: 30,
    armor: 9,
    earthResistance: 40,
    coldResistance: 15,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    damage: 3,
    earthDamage: 1,
    attackRating: 8,
    evasion: 6,
    attackSpeed: 1,
    gold: 8,
    xp: 10,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Thornling',
    element: 'earth',
    image: '/enemies/thornling.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    damage: 3,
    earthDamage: 2,
    earthResistance: 20,
    coldResistance: 10,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    gold: 10,
    attackRating: 11,
    life: 28,
    armor: 6,
    evasion: 8,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Barkhide',
    element: 'earth',
    image: '/enemies/barkhide.jpg',
    tier: tier,
    multiplier: {
      damage: 0.9,
      materialDrop: 1.1,
    },
    life: 34,
    armor: 9,
    earthResistance: 15,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    evasion: 7,
    damage: 2,
    earthDamage: 1,
    attackRating: 7,
    gold: 9,
    xp: 9,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Sylvan Wisp',
    element: 'air',
    image: '/enemies/sylvan-wisp.jpg',
    tier: tier,
    multiplier: {
      life: 0.9,
    },
    life: 24,
    damage: 0,
    evasion: 12,
    airDamage: 3,
    airResistance: 25,
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 5,
    waterResistance: 10,
    attackSpeed: 1.2,
    armor: 4,
    attackRating: 8,
    gold: 10,
    xp: 9,
    materialDropWeights: {},
    tags: ['forest'],
  },
];
