export const GOLDEN_STEPPE_ENEMIES = [
  {
    name: 'Golden Sphinx',
    element: 'earth',
    image: '/enemies/golden-sphinx.jpg',
    tier: 11,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Aurelius',
    element: 'fire',
    image: '/enemies/aurelius.jpg',
    tier: 11,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Midas Beast',
    element: 'air',
    image: '/enemies/midas-beast.jpg',
    tier: 11,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Solar Phoenix',
    element: 'fire',
    image: '/enemies/solar-phoenix.jpg',
    tier: 11,
    multiplier: {
      itemDrop: 1.1,
    },
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: '🔥',
  },
  {
    name: 'Radiant Lion',
    element: 'fire',
    image: '/enemies/radiant-lion.jpg',
    tier: 11,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: '🔥',
  },
];
