export const GOLDEN_STEPPE_ENEMIES = [
  {
    name: 'Golden Sphinx',
    element: 'earth',
    image: '/enemies/golden-sphinx.jpg',
    tier: 11,
    armor: 12,
    earthDamage: 3,
    earthResistance: 25,
    life: 30,
    damage: 4,
    xp: 15,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Aurelius',
    element: 'fire',
    image: '/enemies/aurelius.jpg',
    tier: 11,
    fireDamage: 4,
    gold: 15,
    fireResistance: 20,
    armor: 8,
    earthResistance: 5,
    xp: 15,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Solar Phoenix',
    element: 'fire',
    image: '/enemies/solar-phoenix.jpg',
    tier: 11,
    multiplier: {
      itemDrop: 1.1,
    },
    fireDamage: 5,
    fireResistance: 30,
    life: 32,
    damage: 4,
    airResistance: 10,
    xp: 16,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: '🔥',
  },
  {
    name: 'Radiant Lion',
    element: 'fire',
    image: '/enemies/radiant-lion.jpg',
    tier: 11,
    airDamage: 3,
    life: 28,
    fireResistance: 15,
    armor: 10,
    gold: 12,
    earthResistance: 5,
    xp: 15,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: '🔥',
  },
];
