import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 11;

export const GOLDEN_STEPPE_ENEMIES = [
  {
    name: 'Golden Sphinx',
    element: 'earth',
    image: '/enemies/golden-sphinx.jpg',
    tier: tier,
    armor: 13 * getEnemyStatMultiplier(tier),
    damage: 4 * getEnemyStatMultiplier(tier),
    earthDamage: 3 * getEnemyStatMultiplier(tier),
    earthResistance: 25,
    life: 32 * getEnemyStatMultiplier(tier),
    attackRating: 16 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    fireResistance: 10,
    coldResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 16 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Aurelius',
    element: 'fire',
    image: '/enemies/aurelius.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    gold: 15 * getEnemyStatMultiplier(tier),
    fireResistance: 20,
    armor: 9 * getEnemyStatMultiplier(tier),
    earthResistance: 5,
    coldResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    life: 30 * getEnemyStatMultiplier(tier),
    attackRating: 15 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    xp: 16 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Solar Phoenix',
    element: 'fire',
    image: '/enemies/solar-phoenix.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    damage: 4 * getEnemyStatMultiplier(tier),
    fireDamage: 5 * getEnemyStatMultiplier(tier),
    fireResistance: 30,
    life: 34 * getEnemyStatMultiplier(tier),
    airResistance: 10,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    armor: 12 * getEnemyStatMultiplier(tier),
    attackRating: 17 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    xp: 17 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: '🔥',
  },
  {
    name: 'Radiant Lion',
    element: 'fire',
    image: '/enemies/radiant-lion.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    airDamage: 4 * getEnemyStatMultiplier(tier),
    life: 30 * getEnemyStatMultiplier(tier),
    fireResistance: 15,
    armor: 11 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    earthResistance: 5,
    coldResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    attackRating: 16 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    xp: 16 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: '🔥',
  },
];
