export const HAUNTED_MOOR_ENEMIES = [
  {
    name: 'Banshee',
    element: 'air',
    image: '/enemies/banshee.jpg',
    tier: 10,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Phantom',
    element: 'cold',
    image: '/enemies/phantom.jpg',
    tier: 10,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Wraith Lord',
    element: 'earth',
    image: '/enemies/wraith-lord.jpg',
    tier: 10,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
];
