const tier = 10;

export const HAUNTED_MOOR_ENEMIES = [
  {
    name: 'Banshee',
    element: 'air',
    image: '/enemies/banshee.jpg',
    tier: tier,
    airDamage: 4,
    evasion: 10,
    airResistance: 25,
    coldResistance: 10,
    damage: 3,
    xp: 14,
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Phantom',
    element: 'cold',
    image: '/enemies/phantom.jpg',
    tier: tier,
    coldDamage: 3,
    life: 18,
    coldResistance: 30,
    evasion: 8,
    fireResistance: 5,
    xp: 12,
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Wraith Lord',
    element: 'earth',
    image: '/enemies/wraith-lord.jpg',
    tier: tier,
    earthDamage: 2,
    armor: 9,
    earthResistance: 15,
    life: 26,
    damage: 3,
    attackSpeed: 0.9,
    xp: 13,
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Dreadfang',
    element: 'air',
    image: '/enemies/dreadfang.jpg',
    tier: tier,
    airDamage: 3,
    damage: 4,
    airResistance: 20,
    life: 22,
    evasion: 9,
    xp: 13,
    materialDropWeights: {},
    tags: ['haunted', 'beast'],
  },
];
