import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 10;

export const HAUNTED_MOOR_ENEMIES = [
  {
    name: 'Banshee',
    element: 'air',
    image: '/enemies/banshee.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    airDamage: 4 * getEnemyStatMultiplier(tier),
    evasion: 11 * getEnemyStatMultiplier(tier),
    airResistance: 25,
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 10,
    life: 26 * getEnemyStatMultiplier(tier),
    armor: 6 * getEnemyStatMultiplier(tier),
    attackRating: 15 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.1 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 15 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Phantom',
    element: 'cold',
    image: '/enemies/phantom.jpg',
    tier: tier,
    damage: 1 * getEnemyStatMultiplier(tier),
    coldDamage: 4 * getEnemyStatMultiplier(tier),
    life: 20 * getEnemyStatMultiplier(tier),
    coldResistance: 30,
    evasion: 8 * getEnemyStatMultiplier(tier),
    fireResistance: 5,
    airResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 10,
    armor: 6 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.0 * getEnemyStatMultiplier(tier),
    gold: 11 * getEnemyStatMultiplier(tier),
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Wraith Lord',
    element: 'earth',
    image: '/enemies/wraith-lord.jpg',
    tier: tier,
    damage: 4 * getEnemyStatMultiplier(tier),
    earthDamage: 3 * getEnemyStatMultiplier(tier),
    armor: 10 * getEnemyStatMultiplier(tier),
    earthResistance: 15,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 10,
    life: 28 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    attackRating: 16 * getEnemyStatMultiplier(tier),
    gold: 13 * getEnemyStatMultiplier(tier),
    xp: 14 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Dreadfang',
    element: 'air',
    image: '/enemies/dreadfang.jpg',
    tier: tier,
    airDamage: 3 * getEnemyStatMultiplier(tier),
    damage: 4 * getEnemyStatMultiplier(tier),
    airResistance: 20,
    fireResistance: 5,
    coldResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    life: 24 * getEnemyStatMultiplier(tier),
    evasion: 10 * getEnemyStatMultiplier(tier),
    armor: 8 * getEnemyStatMultiplier(tier),
    attackRating: 15 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.2 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 14 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['haunted', 'beast'],
  },
];
