import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 5;

export const SWAMP_ENEMIES = [
  {
    name: 'Boglurker',
    element: 'earth',
    image: '/enemies/boglurker.jpg',
    tier: tier,
    life: 24 * getEnemyStatMultiplier(tier),
    damage: 2 * getEnemyStatMultiplier(tier),
    earthDamage: 3 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    armor: 8 * getEnemyStatMultiplier(tier),
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 20,
    xp: 10 * getEnemyStatMultiplier(tier),
    attackRating: 12 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    gold: 9 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['swamp', 'poison'],
  },
  {
    name: 'Toxictoad',
    element: 'earth',
    image: '/enemies/toxictoad.jpg',
    tier: tier,
    coldResistance: 10,
    earthResistance: 15,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 20,
    damage: 2 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9,
    evasion: 7 * getEnemyStatMultiplier(tier),
    life: 22 * getEnemyStatMultiplier(tier),
    armor: 7 * getEnemyStatMultiplier(tier),
    attackRating: 11 * getEnemyStatMultiplier(tier),
    gold: 8 * getEnemyStatMultiplier(tier),
    xp: 9 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['swamp', 'toxic'],
  },
  {
    name: 'Venomspitter',
    element: 'earth',
    image: '/enemies/venomspitter.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.2,
    earthResistance: 5,
    life: 20 * getEnemyStatMultiplier(tier),
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 15,
    armor: 6 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    attackRating: 12 * getEnemyStatMultiplier(tier),
    gold: 9 * getEnemyStatMultiplier(tier),
    xp: 10 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['swamp', 'venom'],
  },
  {
    name: 'Frostweaver',
    element: 'cold',
    image: '/enemies/frostweaver.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    coldDamage: 5 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    coldResistance: 25,
    fireResistance: 5,
    armor: 7 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9,
    life: 22 * getEnemyStatMultiplier(tier),
    attackRating: 10 * getEnemyStatMultiplier(tier),
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 15,
    gold: 10 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['swamp', 'ice'],
  },
];
