import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 12;

export const OBSIDIAN_SPIRE_ENEMIES = [
  {
    name: 'Void Sentinel',
    element: 'cold',
    image: '/enemies/void-sentinel.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
      materialDrop: 1.2,
    },
    damage: 1 * getEnemyStatMultiplier(tier),
    coldDamage: 3 * getEnemyStatMultiplier(tier),
    coldResistance: 60,
    fireResistance: 5,
    airResistance: 30,
    earthResistance: 30,
    lightningResistance: 25,
    waterResistance: 45,
    life: 18 * getEnemyStatMultiplier(tier),
    attackRating: 10 * getEnemyStatMultiplier(tier),
    evasion: 10 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Obsidian Golem',
    element: 'earth',
    image: '/enemies/obsidian-golem.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.4,
    },
    armor: 15 * getEnemyStatMultiplier(tier),
    damage: 2 * getEnemyStatMultiplier(tier),
    earthDamage: 2.5 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.7,
    earthResistance: 70,
    coldResistance: 20,
    fireResistance: 25,
    airResistance: 15,
    lightningResistance: 20,
    waterResistance: 20,
    life: 28 * getEnemyStatMultiplier(tier),
    attackRating: 4.5 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Crimson Wisp',
    element: 'fire',
    image: '/enemies/crimson-wisp.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.2,
    },
    damage: 0 * getEnemyStatMultiplier(tier),
    fireDamage: 2 * getEnemyStatMultiplier(tier),
    fireResistance: 45,
    coldResistance: 25,
    airResistance: 30,
    earthResistance: 20,
    lightningResistance: 20,
    waterResistance: 20,
    airDamage: 1 * getEnemyStatMultiplier(tier),
    life: 16 * getEnemyStatMultiplier(tier),
    attackRating: 8 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: '🔥',
  },
  {
    name: 'Flame Djinn',
    element: 'fire',
    image: '/enemies/flame-djinn.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.5,
    },
    damage: 1.2 * getEnemyStatMultiplier(tier),
    fireDamage: 1.8 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9,
    fireResistance: 50,
    coldResistance: 30,
    airResistance: 30,
    earthResistance: 25,
    lightningResistance: 25,
    waterResistance: 0,
    life: 24 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: '🔥',
  },
];
