import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 12;

export const OBSIDIAN_SPIRE_ENEMIES = [
  {
    name: 'Void Sentinel',
    element: 'cold',
    image: '/enemies/void-sentinel.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
      materialDrop: 1.2,
    },
    damage: 0 * getEnemyStatMultiplier(tier),
    coldDamage: 5 * getEnemyStatMultiplier(tier),
    coldResistance: 30,
    fireResistance: 5,
    airResistance: 10,
    earthResistance: 20,
    lightningResistance: 20,
    waterResistance: 15,
    life: 36 * getEnemyStatMultiplier(tier),
    armor: 13 * getEnemyStatMultiplier(tier),
    attackRating: 18 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 18 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Obsidian Golem',
    element: 'earth',
    image: '/enemies/obsidian-golem.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.4,
    },
    armor: 15 * getEnemyStatMultiplier(tier),
    damage: 4 * getEnemyStatMultiplier(tier),
    earthDamage: 4 * getEnemyStatMultiplier(tier),
    earthResistance: 40,
    coldResistance: 10,
    fireResistance: 15,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 10,
    life: 38 * getEnemyStatMultiplier(tier),
    attackRating: 20 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    gold: 14 * getEnemyStatMultiplier(tier),
    xp: 18 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Crimson Wisp',
    element: 'fire',
    image: '/enemies/crimson-wisp.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.2,
    },
    damage: 0 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    evasion: 11 * getEnemyStatMultiplier(tier),
    fireResistance: 25,
    coldResistance: 15,
    airResistance: 20,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 10,
    airDamage: 2 * getEnemyStatMultiplier(tier),
    life: 26 * getEnemyStatMultiplier(tier),
    armor: 9 * getEnemyStatMultiplier(tier),
    attackRating: 19 * getEnemyStatMultiplier(tier),
    gold: 13 * getEnemyStatMultiplier(tier),
    xp: 17 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: '🔥',
  },
  {
    name: 'Flame Djinn',
    element: 'fire',
    image: '/enemies/flame-djinn.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.5,
    },
    damage: 4 * getEnemyStatMultiplier(tier),
    fireDamage: 5 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9 * getEnemyStatMultiplier(tier),
    fireResistance: 40,
    coldResistance: 10,
    airResistance: 10,
    earthResistance: 15,
    lightningResistance: 15,
    waterResistance: 5,
    life: 32 * getEnemyStatMultiplier(tier),
    armor: 12 * getEnemyStatMultiplier(tier),
    attackRating: 20 * getEnemyStatMultiplier(tier),
    evasion: 9 * getEnemyStatMultiplier(tier),
    gold: 15 * getEnemyStatMultiplier(tier),
    xp: 18 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: '🔥',
  },
];
