const tier = 12;

export const OBSIDIAN_SPIRE_ENEMIES = [
  {
    name: 'Void Sentinel',
    element: 'cold',
    image: '/enemies/void-sentinel.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
      materialDrop: 1.2,
    },
    coldDamage: 4,
    coldResistance: 30,
    fireResistance: 5,
    life: 34,
    armor: 12,
    xp: 17,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Obsidian Golem',
    element: 'earth',
    image: '/enemies/obsidian-golem.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.4,
    },
    armor: 14,
    earthDamage: 3,
    earthResistance: 40,
    life: 36,
    damage: 4,
    xp: 18,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Crimson Wisp',
    element: 'fire',
    image: '/enemies/crimson-wisp.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.2,
    },
    fireDamage: 3,
    evasion: 10,
    fireResistance: 25,
    airDamage: 2,
    life: 24,
    xp: 16,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: '🔥',
  },
  {
    name: 'Flame Djinn',
    element: 'fire',
    image: '/enemies/flame-djinn.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.5,
    },
    fireDamage: 5,
    attackSpeed: 0.9,
    fireResistance: 40,
    life: 30,
    damage: 4,
    xp: 18,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: '🔥',
  },
];
