import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 4;

export const DESERT_ENEMIES = [
  {
    name: 'Dunewraith',
    element: 'earth',
    image: '/enemies/dunewraith.jpg',
    tier: tier,
    damage: 2 * getEnemyStatMultiplier(tier),
    earthDamage: 3 * getEnemyStatMultiplier(tier),
    earthResistance: 20,
    coldResistance: 15,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    armor: 7 * getEnemyStatMultiplier(tier),
    evasion: 9 * getEnemyStatMultiplier(tier),
    life: 26 * getEnemyStatMultiplier(tier),
    attackRating: 12 * getEnemyStatMultiplier(tier),
    gold: 9 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['desert', 'undead'],
  },
  {
    name: 'Sandstalker',
    element: 'earth',
    image: '/enemies/sandstalker.jpg',
    tier: tier,
    evasion: 13 * getEnemyStatMultiplier(tier),
    damage: 0 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.1,
    life: 24 * getEnemyStatMultiplier(tier),
    armor: 6 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    attackRating: 12 * getEnemyStatMultiplier(tier),
    gold: 9 * getEnemyStatMultiplier(tier),
    xp: 10 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['desert', 'scorpion'],
  },
  {
    name: 'Scorching Salamander',
    element: 'fire',
    image: '/enemies/scorching-salamander.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    fireResistance: 30,
    coldResistance: 20,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 10,
    life: 28 * getEnemyStatMultiplier(tier),
    earthResistance: 5,
    armor: 8 * getEnemyStatMultiplier(tier),
    attackRating: 12 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.0,
    gold: 10 * getEnemyStatMultiplier(tier),
    xp: 12 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['desert', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Dune Blazer',
    element: 'fire',
    image: '/enemies/dune-blazer.jpg',
    tier: tier,
    damage: 3 * getEnemyStatMultiplier(tier),
    fireDamage: 3 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    attackSpeed: 1.1,
    coldResistance: 5,
    fireResistance: 20,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    evasion: 8 * getEnemyStatMultiplier(tier),
    life: 26 * getEnemyStatMultiplier(tier),
    armor: 7 * getEnemyStatMultiplier(tier),
    attackRating: 12 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    gold: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['desert', 'sand'],
    icon: '🔥',
  },
];
