import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 6;

export const SKYREALM_ENEMIES = [
  {
    name: 'Cloudstrider',
    element: 'air',
    image: '/enemies/cloudstrider.jpg',
    tier: tier,
    damage: 1 * getEnemyStatMultiplier(tier),
    airDamage: 3 * getEnemyStatMultiplier(tier),
    airResistance: 20,
    coldResistance: 5,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    evasion: 11 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.2 * getEnemyStatMultiplier(tier),
    life: 24 * getEnemyStatMultiplier(tier),
    armor: 6 * getEnemyStatMultiplier(tier),
    attackRating: 12 * getEnemyStatMultiplier(tier),
    gold: 10 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['skyrealm', 'air'],
  },
  {
    name: 'Stormbringer',
    element: 'air',
    image: '/enemies/stormbringer.jpg',
    tier: tier,
    damage: 4 * getEnemyStatMultiplier(tier),
    airDamage: 1 * getEnemyStatMultiplier(tier),
    airResistance: 15,
    coldResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    life: 28 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    fireResistance: 5,
    armor: 7 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.1 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 12 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['skyrealm', 'storm'],
  },
  {
    name: 'Stormsoul',
    element: 'air',
    image: '/enemies/stormsoul.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    airDamage: 4 * getEnemyStatMultiplier(tier),
    airResistance: 30,
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    evasion: 9 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.1 * getEnemyStatMultiplier(tier),
    life: 26 * getEnemyStatMultiplier(tier),
    armor: 6 * getEnemyStatMultiplier(tier),
    attackRating: 13 * getEnemyStatMultiplier(tier),
    gold: 11 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['skyrealm', 'soul'],
  },
  {
    name: 'Midas Beast',
    element: 'air',
    image: '/enemies/midas-beast.jpg',
    tier: tier,
    gold: 15 * getEnemyStatMultiplier(tier),
    armor: 15 * getEnemyStatMultiplier(tier),
    life: 30 * getEnemyStatMultiplier(tier),
    damage: 4 * getEnemyStatMultiplier(tier),
    airDamage: 2 * getEnemyStatMultiplier(tier),
    airResistance: 15,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    attackRating: 14 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.2 * getEnemyStatMultiplier(tier),
    fireResistance: 5,
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['skyrealm', 'gold'],
  },
];
