export const SKYREALM_ENEMIES = [
  {
    name: 'Cloudstrider',
    element: 'air',
    image: '/enemies/cloudstrider.jpg',
    tier: 6,
    airDamage: 3,
    airResistance: 20,
    damage: 2,
    evasion: 10,
    attackSpeed: 1.2,
    xp: 10,
    materialDropWeights: {},
    tags: ['skyrealm', 'air'],
  },
  {
    name: 'Stormbringer',
    element: 'air',
    image: '/enemies/stormbringer.jpg',
    tier: 6,
    damage: 5,
    airResistance: 15,
    life: 26,
    attackRating: 13,
    fireResistance: 5,
    xp: 11,
    materialDropWeights: {},
    tags: ['skyrealm', 'storm'],
  },
  {
    name: 'Stormsoul',
    element: 'air',
    image: '/enemies/stormsoul.jpg',
    tier: 6,
    airDamage: 4,
    airResistance: 30,
    coldResistance: 10,
    evasion: 8,
    attackSpeed: 1.1,
    xp: 10,
    materialDropWeights: {},
    tags: ['skyrealm', 'soul'],
  },
  {
    name: 'Midas Beast',
    element: 'air',
    image: '/enemies/midas-beast.jpg',
    tier: 6,
    gold: 15,
    armor: 15,
    life: 28,
    damage: 4,
    airResistance: 15,
    xp: 12,
    materialDropWeights: {},
    tags: ['skyrealm', 'gold'],
  },
];
