const tier = 6;

export const SKYREALM_ENEMIES = [
  {
    name: 'Cloudstrider',
    element: 'air',
    image: '/enemies/cloudstrider.jpg',
    tier: tier,
    damage: 0,
    airDamage: 3,
    airResistance: 20,
    coldResistance: 5,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    evasion: 11,
    attackSpeed: 1.2,
    life: 24,
    armor: 6,
    attackRating: 12,
    gold: 10,
    xp: 11,
    materialDropWeights: {},
    tags: ['skyrealm', 'air'],
  },
  {
    name: 'Stormbringer',
    element: 'air',
    image: '/enemies/stormbringer.jpg',
    tier: tier,
    damage: 4,
    airDamage: 1,
    airResistance: 15,
    coldResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    life: 28,
    attackRating: 14,
    fireResistance: 5,
    armor: 7,
    evasion: 8,
    attackSpeed: 1.1,
    gold: 12,
    xp: 12,
    materialDropWeights: {},
    tags: ['skyrealm', 'storm'],
  },
  {
    name: 'Stormsoul',
    element: 'air',
    image: '/enemies/stormsoul.jpg',
    tier: tier,
    damage: 0,
    airDamage: 4,
    airResistance: 30,
    coldResistance: 10,
    fireResistance: 5,
    earthResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    evasion: 9,
    attackSpeed: 1.1,
    life: 26,
    armor: 6,
    attackRating: 13,
    gold: 11,
    xp: 11,
    materialDropWeights: {},
    tags: ['skyrealm', 'soul'],
  },
  {
    name: 'Midas Beast',
    element: 'air',
    image: '/enemies/midas-beast.jpg',
    tier: tier,
    gold: 15,
    armor: 15,
    life: 30,
    damage: 4,
    airDamage: 2,
    airResistance: 15,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    attackRating: 14,
    evasion: 7,
    attackSpeed: 1.2,
    fireResistance: 5,
    xp: 13,
    materialDropWeights: {},
    tags: ['skyrealm', 'gold'],
  },
];
