export const SKYREALM_ENEMIES = [
  {
    name: 'Cloudstrider',
    element: 'air',
    image: '/enemies/cloudstrider.jpg',
    tier: 6,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['skyrealm', 'air'],
  },
  {
    name: 'Stormbringer',
    element: 'air',
    image: '/enemies/stormbringer.jpg',
    tier: 6,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['storm', 'air'],
  },
  {
    name: 'Stormsoul',
    element: 'air',
    image: '/enemies/stormsoul.jpg',
    tier: 6,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['storm', 'soul', 'sky'],
  },
  {
    name: 'Thunderwing',
    element: 'air',
    image: '/enemies/thunderwing.jpg',
    tier: 6,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['thunder', 'air'],
  },
];
