const tier = 9;

export const SUNKEN_RUINS_ENEMIES = [
  {
    name: 'Tide Guardian',
    element: 'cold',
    image: '/enemies/tide-guardian.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.2,
    },
    damage: 0,
    coldDamage: 3,
    armor: 9,
    coldResistance: 30,
    life: 30,
    earthResistance: 10,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 20,
    attackRating: 15,
    evasion: 6,
    attackSpeed: 0.95,
    gold: 12,
    xp: 14,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Coral Sentinel',
    element: 'earth',
    image: '/enemies/coral-sentinel.jpg',
    tier: tier,
    damage: 4,
    earthDamage: 2,
    life: 26,
    earthResistance: 25,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 15,
    armor: 11,
    attackRating: 14,
    evasion: 6,
    attackSpeed: 1.0,
    gold: 11,
    xp: 13,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Depths Leviathan',
    element: 'cold',
    image: '/enemies/depths-leviathan.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    coldDamage: 4,
    attackSpeed: 0.8,
    coldResistance: 40,
    life: 32,
    damage: 5,
    armor: 12,
    airResistance: 10,
    earthResistance: 10,
    fireResistance: 5,
    lightningResistance: 10,
    waterResistance: 25,
    attackRating: 16,
    evasion: 5,
    gold: 15,
    xp: 15,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Arcane Construct',
    element: 'air',
    image: '/enemies/arcane-construct.jpg',
    tier: tier,
    damage: 0,
    airDamage: 3,
    airResistance: 15,
    coldResistance: 10,
    earthResistance: 5,
    fireResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    armor: 8,
    evasion: 9,
    life: 24,
    attackRating: 13,
    attackSpeed: 1.2,
    gold: 11,
    xp: 12,
    materialDropWeights: {},
    tags: ['ruins', 'arcane'],
  },
];
