import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 9;

export const SUNKEN_RUINS_ENEMIES = [
  {
    name: 'Tide Guardian',
    element: 'cold',
    image: '/enemies/tide-guardian.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.2,
    },
    damage: 0 * getEnemyStatMultiplier(tier),
    coldDamage: 3 * getEnemyStatMultiplier(tier),
    armor: 9 * getEnemyStatMultiplier(tier),
    coldResistance: 30,
    life: 30 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 20,
    attackRating: 15 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.95,
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 14 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Coral Sentinel',
    element: 'earth',
    image: '/enemies/coral-sentinel.jpg',
    tier: tier,
    damage: 4 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    life: 26 * getEnemyStatMultiplier(tier),
    earthResistance: 25,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 10,
    waterResistance: 15,
    armor: 11 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.0,
    gold: 11 * getEnemyStatMultiplier(tier),
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Depths Leviathan',
    element: 'cold',
    image: '/enemies/depths-leviathan.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    coldDamage: 4 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.8,
    coldResistance: 40,
    life: 32 * getEnemyStatMultiplier(tier),
    damage: 5 * getEnemyStatMultiplier(tier),
    armor: 12 * getEnemyStatMultiplier(tier),
    airResistance: 10,
    earthResistance: 10,
    fireResistance: 5,
    lightningResistance: 10,
    waterResistance: 25,
    attackRating: 16 * getEnemyStatMultiplier(tier),
    evasion: 5 * getEnemyStatMultiplier(tier),
    gold: 15 * getEnemyStatMultiplier(tier),
    xp: 15 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Arcane Construct',
    element: 'air',
    image: '/enemies/arcane-construct.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    airDamage: 3 * getEnemyStatMultiplier(tier),
    airResistance: 15,
    coldResistance: 10,
    earthResistance: 5,
    fireResistance: 5,
    lightningResistance: 10,
    waterResistance: 5,
    armor: 8 * getEnemyStatMultiplier(tier),
    evasion: 9 * getEnemyStatMultiplier(tier),
    life: 24 * getEnemyStatMultiplier(tier),
    attackRating: 13 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.2,
    gold: 11 * getEnemyStatMultiplier(tier),
    xp: 12 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['ruins', 'arcane'],
  },
];
