const tier = 9;

export const SUNKEN_RUINS_ENEMIES = [
  {
    name: 'Tide Guardian',
    element: 'cold',
    image: '/enemies/tide-guardian.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.2,
    },
    coldDamage: 3,
    armor: 8,
    coldResistance: 30,
    life: 28,
    earthResistance: 10,
    xp: 13,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Coral Sentinel',
    element: 'earth',
    image: '/enemies/coral-sentinel.jpg',
    tier: tier,
    earthDamage: 2,
    life: 24,
    earthResistance: 25,
    armor: 10,
    damage: 3,
    xp: 12,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Depths Leviathan',
    element: 'cold',
    image: '/enemies/depths-leviathan.jpg',
    tier: tier,
    multiplier: {
      itemDrop: 1.1,
    },
    coldDamage: 4,
    attackSpeed: 0.8,
    coldResistance: 40,
    life: 30,
    damage: 5,
    xp: 14,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Arcane Construct',
    element: 'air',
    image: '/enemies/arcane-construct.jpg',
    tier: tier,
    airDamage: 3,
    airResistance: 15,
    coldResistance: 10,
    armor: 7,
    evasion: 8,
    xp: 11,
    materialDropWeights: {},
    tags: ['ruins', 'arcane'],
  },
];
