const tier = 5;

export const SWAMP_ENEMIES = [
  {
    name: 'Boglurker',
    element: 'earth',
    image: '/enemies/boglurker.jpg',
    tier: tier,
    life: 22,
    earthDamage: 2,
    earthResistance: 10,
    armor: 7,
    coldResistance: 5,
    xp: 9,
    attackRating: 11,
    materialDropWeights: {},
    tags: ['swamp', 'poison'],
  },
  {
    name: 'Toxictoad',
    element: 'earth',
    image: '/enemies/toxictoad.jpg',
    tier: tier,
    coldResistance: 10,
    earthResistance: 15,
    damage: 2,
    attackSpeed: 0.9,
    evasion: 6,
    xp: 8,
    materialDropWeights: {},
    tags: ['swamp', 'toxic'],
  },
  {
    name: 'Venomspitter',
    element: 'earth',
    image: '/enemies/venomspitter.jpg',
    tier: tier,
    damage: 4,
    attackSpeed: 1.2,
    earthResistance: 5,
    life: 18,
    coldResistance: 5,
    xp: 9,
    materialDropWeights: {},
    tags: ['swamp', 'venom'],
  },
  {
    name: 'Frostweaver',
    element: 'cold',
    image: '/enemies/frostweaver.jpg',
    tier: tier,
    coldDamage: 5,
    earthResistance: 10,
    coldResistance: 25,
    armor: 6,
    evasion: 7,
    attackSpeed: 0.9,
    xp: 10,
    materialDropWeights: {},
    tags: ['swamp', 'ice'],
  },
];
