export const SWAMP_ENEMIES = [
  {
    name: 'Boglurker',
    element: 'earth',
    image: '/enemies/boglurker.jpg',
    tier: 5,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['swamp', 'poison'],
  },
  {
    name: 'Toxictoad',
    element: 'earth',
    image: '/enemies/toxictoad.jpg',
    tier: 5,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['toxic', 'frog', 'swamp'],
  },
  {
    name: 'Venomspitter',
    element: 'earth',
    image: '/enemies/venomspitter.jpg',
    tier: 5,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {},
    tags: ['venom', 'spider', 'swamp'],
  },
];
