const tier = 5;

export const SWAMP_ENEMIES = [
  {
    name: 'Boglurker',
    element: 'earth',
    image: '/enemies/boglurker.jpg',
    tier: tier,
    life: 24,
    damage: 2,
    earthDamage: 3,
    earthResistance: 10,
    armor: 8,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 20,
    xp: 10,
    attackRating: 12,
    evasion: 6,
    gold: 9,
    materialDropWeights: {},
    tags: ['swamp', 'poison'],
  },
  {
    name: 'Toxictoad',
    element: 'earth',
    image: '/enemies/toxictoad.jpg',
    tier: tier,
    coldResistance: 10,
    earthResistance: 15,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 20,
    damage: 2,
    earthDamage: 2,
    attackSpeed: 0.9,
    evasion: 7,
    life: 22,
    armor: 7,
    attackRating: 11,
    gold: 8,
    xp: 9,
    materialDropWeights: {},
    tags: ['swamp', 'toxic'],
  },
  {
    name: 'Venomspitter',
    element: 'earth',
    image: '/enemies/venomspitter.jpg',
    tier: tier,
    damage: 0,
    earthDamage: 2,
    attackSpeed: 1.2,
    earthResistance: 5,
    life: 20,
    coldResistance: 5,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 15,
    armor: 6,
    evasion: 8,
    attackRating: 12,
    gold: 9,
    xp: 10,
    materialDropWeights: {},
    tags: ['swamp', 'venom'],
  },
  {
    name: 'Frostweaver',
    element: 'cold',
    image: '/enemies/frostweaver.jpg',
    tier: tier,
    damage: 0,
    coldDamage: 5,
    earthResistance: 10,
    coldResistance: 25,
    fireResistance: 5,
    armor: 7,
    evasion: 7,
    attackSpeed: 0.9,
    life: 22,
    attackRating: 10,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 15,
    gold: 10,
    xp: 11,
    materialDropWeights: {},
    tags: ['swamp', 'ice'],
  },
];
