import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 3;

export const TUNDRA_ENEMIES = [
  {
    name: 'Frostbite',
    element: 'cold',
    image: '/enemies/frostbite.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    airDamage: 3 * getEnemyStatMultiplier(tier),
    coldDamage: 3 * getEnemyStatMultiplier(tier),
    coldResistance: 25,
    fireResistance: 5,
    earthResistance: 10,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 10,
    life: 26 * getEnemyStatMultiplier(tier),
    armor: 9 * getEnemyStatMultiplier(tier),
    attackRating: 10 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9 * getEnemyStatMultiplier(tier),
    gold: 9 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['ice', 'cold'],
  },
  {
    name: 'Frostfury',
    element: 'cold',
    image: '/enemies/frostfury.jpg',
    tier: tier,
    damage: 4 * getEnemyStatMultiplier(tier),
    coldDamage: 1 * getEnemyStatMultiplier(tier),
    coldResistance: 20,
    earthResistance: 10,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 10,
    armor: 7 * getEnemyStatMultiplier(tier),
    life: 24 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    attackRating: 11 * getEnemyStatMultiplier(tier),
    fireResistance: 5,
    xp: 10 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['ice', 'fury'],
  },
  {
    name: 'Frost Giant',
    element: 'cold',
    image: '/enemies/frost-giant.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    life: 32 * getEnemyStatMultiplier(tier),
    armor: 11 * getEnemyStatMultiplier(tier),
    damage: 3 * getEnemyStatMultiplier(tier),
    coldDamage: 2 * getEnemyStatMultiplier(tier),
    coldResistance: 20,
    fireResistance: 5,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 10,
    attackRating: 15 * getEnemyStatMultiplier(tier),
    evasion: 5 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.95 * getEnemyStatMultiplier(tier),
    earthResistance: 10,
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 12 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
  {
    name: 'Ice Wraith',
    element: 'cold',
    image: '/enemies/ice-wraith.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    coldDamage: 3 * getEnemyStatMultiplier(tier),
    evasion: 13 * getEnemyStatMultiplier(tier),
    coldResistance: 30,
    fireResistance: 5,
    airResistance: 5,
    earthResistance: 5,
    lightningResistance: 5,
    waterResistance: 15,
    life: 22 * getEnemyStatMultiplier(tier),
    armor: 6 * getEnemyStatMultiplier(tier),
    attackRating: 9 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.1 * getEnemyStatMultiplier(tier),
    gold: 8 * getEnemyStatMultiplier(tier),
    xp: 10 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
];
