export const TUNDRA_ENEMIES = [
  {
    name: 'Frostbite',
    element: 'cold',
    image: '/enemies/frostbite.jpg',
    tier: 3,
    materialDropWeights: {},
    tags: ['ice', 'cold'],
  },
  {
    name: 'Frostfury',
    element: 'cold',
    image: '/enemies/frostfury.jpg',
    tier: 3,
    materialDropWeights: {},
    tags: ['ice', 'fury'],
  },
  {
    name: 'Frostweaver',
    element: 'cold',
    image: '/enemies/frostweaver.jpg',
    tier: 3,
    materialDropWeights: {},
    tags: ['ice', 'spider'],
  },
  {
    name: 'Frost Giant',
    element: 'cold',
    image: '/enemies/frost-giant.jpg',
    tier: 3,
    multiplier: {
      materialDrop: 1.1,
    },
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
  {
    name: 'Ice Wraith',
    element: 'cold',
    image: '/enemies/ice-wraith.jpg',
    tier: 3,
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
];
