const tier = 3;

export const TUNDRA_ENEMIES = [
  {
    name: 'Frostbite',
    element: 'cold',
    image: '/enemies/frostbite.jpg',
    tier: tier,
    coldDamage: 3,
    coldResistance: 25,
    fireResistance: 5,
    life: 24,
    armor: 8,
    xp: 10,
    materialDropWeights: {},
    tags: ['ice', 'cold'],
  },
  {
    name: 'Frostfury',
    element: 'cold',
    image: '/enemies/frostfury.jpg',
    tier: tier,
    damage: 4,
    coldResistance: 20,
    armor: 6,
    xp: 9,
    materialDropWeights: {},
    tags: ['ice', 'fury'],
  },
  {
    name: 'Frost Giant',
    element: 'cold',
    image: '/enemies/frost-giant.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    life: 30,
    armor: 10,
    coldResistance: 20,
    attackRating: 14,
    xp: 11,
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
  {
    name: 'Ice Wraith',
    element: 'cold',
    image: '/enemies/ice-wraith.jpg',
    tier: tier,
    evasion: 12,
    coldResistance: 30,
    damage: 3,
    xp: 9,
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
];
