import { getEnemyStatMultiplier } from '../enemies.js';

const tier = 8;

export const VOLCANIC_RIFT_ENEMIES = [
  {
    name: 'Magma Titan',
    element: 'fire',
    image: '/enemies/magma-titan.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.2,
    },
    life: 38 * getEnemyStatMultiplier(tier),
    damage: 4 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    fireResistance: 40,
    earthResistance: 15,
    coldResistance: 10,
    airResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    armor: 13 * getEnemyStatMultiplier(tier),
    attackRating: 16 * getEnemyStatMultiplier(tier),
    evasion: 6 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9 * getEnemyStatMultiplier(tier),
    gold: 14 * getEnemyStatMultiplier(tier),
    xp: 15 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Lava Elemental',
    element: 'fire',
    image: '/enemies/lava-elemental.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    damage: 0 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    fireResistance: 30,
    earthResistance: 10,
    coldResistance: 5,
    airResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    armor: 9 * getEnemyStatMultiplier(tier),
    attackSpeed: 0.9 * getEnemyStatMultiplier(tier),
    life: 32 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    evasion: 7 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Wildfire Spirit',
    element: 'fire',
    image: '/enemies/wildfire-spirit.jpg',
    tier: tier,
    damage: 0 * getEnemyStatMultiplier(tier),
    airResistance: 5,
    fireDamage: 3,
    fireResistance: 25,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    life: 26 * getEnemyStatMultiplier(tier),
    earthDamage: 1 * getEnemyStatMultiplier(tier),
    armor: 8 * getEnemyStatMultiplier(tier),
    evasion: 9 * getEnemyStatMultiplier(tier),
    attackRating: 13 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.1 * getEnemyStatMultiplier(tier),
    gold: 11 * getEnemyStatMultiplier(tier),
    xp: 12 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Molten Wyrm',
    element: 'fire',
    image: '/enemies/molten-wyrm.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.3,
    },
    damage: 4 * getEnemyStatMultiplier(tier),
    fireDamage: 4 * getEnemyStatMultiplier(tier),
    armor: 11 * getEnemyStatMultiplier(tier),
    fireResistance: 30,
    earthResistance: 10,
    coldResistance: 10,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    life: 34 * getEnemyStatMultiplier(tier),
    earthDamage: 2 * getEnemyStatMultiplier(tier),
    evasion: 8 * getEnemyStatMultiplier(tier),
    attackRating: 15 * getEnemyStatMultiplier(tier),
    attackSpeed: 1.0 * getEnemyStatMultiplier(tier),
    gold: 14 * getEnemyStatMultiplier(tier),
    xp: 13 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Thunderwing',
    element: 'air',
    image: '/enemies/thunderwing.jpg',
    tier: tier,
    damage: 2 * getEnemyStatMultiplier(tier),
    airDamage: 4 * getEnemyStatMultiplier(tier),
    fireResistance: 10,
    airResistance: 20,
    coldResistance: 5,
    earthResistance: 5,
    lightningResistance: 15,
    waterResistance: 5,
    attackSpeed: 1.3 * getEnemyStatMultiplier(tier),
    life: 28 * getEnemyStatMultiplier(tier),
    armor: 7 * getEnemyStatMultiplier(tier),
    evasion: 9 * getEnemyStatMultiplier(tier),
    attackRating: 14 * getEnemyStatMultiplier(tier),
    gold: 12 * getEnemyStatMultiplier(tier),
    xp: 11 * getEnemyStatMultiplier(tier),
    materialDropWeights: {},
    tags: ['volcano', 'air'],
  },
];
