const tier = 8;

export const VOLCANIC_RIFT_ENEMIES = [
  {
    name: 'Magma Titan',
    element: 'fire',
    image: '/enemies/magma-titan.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.2,
    },
    life: 35,
    fireDamage: 5,
    fireResistance: 40,
    earthDamage: 2,
    armor: 12,
    damage: 4,
    xp: 14,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Lava Elemental',
    element: 'fire',
    image: '/enemies/lava-elemental.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    fireDamage: 4,
    earthDamage: 2,
    fireResistance: 30,
    armor: 8,
    attackSpeed: 0.9,
    xp: 12,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Wildfire Spirit',
    element: 'fire',
    image: '/enemies/wildfire-spirit.jpg',
    tier: tier,
    damage: 3,
    airResistance: 5,
    fireDamage: 3,
    fireResistance: 25,
    life: 24,
    attackSpeed: 1.1,
    xp: 11,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Molten Wyrm',
    element: 'fire',
    image: '/enemies/molten-wyrm.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.3,
    },
    fireDamage: 5,
    armor: 10,
    fireResistance: 30,
    life: 32,
    earthDamage: 2,
    xp: 12,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Thunderwing',
    element: 'air',
    image: '/enemies/thunderwing.jpg',
    tier: tier,
    airDamage: 4,
    fireResistance: 10,
    airResistance: 20,
    damage: 3,
    attackSpeed: 1.3,
    xp: 10,
    materialDropWeights: {},
    tags: ['volcano', 'air'],
  },
];
