const tier = 8;

export const VOLCANIC_RIFT_ENEMIES = [
  {
    name: 'Magma Titan',
    element: 'fire',
    image: '/enemies/magma-titan.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.2,
    },
    life: 38,
    damage: 4,
    fireDamage: 4,
    fireResistance: 40,
    earthResistance: 15,
    coldResistance: 10,
    airResistance: 10,
    lightningResistance: 10,
    waterResistance: 5,
    earthDamage: 2,
    armor: 13,
    attackRating: 16,
    evasion: 6,
    attackSpeed: 0.9,
    gold: 14,
    xp: 15,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Lava Elemental',
    element: 'fire',
    image: '/enemies/lava-elemental.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.1,
    },
    damage: 0,
    fireDamage: 4,
    earthDamage: 2,
    fireResistance: 30,
    earthResistance: 10,
    coldResistance: 5,
    airResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    armor: 9,
    attackSpeed: 0.9,
    life: 32,
    attackRating: 14,
    evasion: 7,
    gold: 12,
    xp: 13,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Wildfire Spirit',
    element: 'fire',
    image: '/enemies/wildfire-spirit.jpg',
    tier: tier,
    damage: 0,
    airResistance: 5,
    fireDamage: 3,
    fireResistance: 25,
    coldResistance: 5,
    earthResistance: 10,
    lightningResistance: 5,
    waterResistance: 5,
    life: 26,
    earthDamage: 1,
    armor: 8,
    evasion: 9,
    attackRating: 13,
    attackSpeed: 1.1,
    gold: 11,
    xp: 12,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Molten Wyrm',
    element: 'fire',
    image: '/enemies/molten-wyrm.jpg',
    tier: tier,
    multiplier: {
      materialDrop: 1.3,
    },
    damage: 4,
    fireDamage: 4,
    armor: 11,
    fireResistance: 30,
    earthResistance: 10,
    coldResistance: 10,
    airResistance: 5,
    lightningResistance: 5,
    waterResistance: 5,
    life: 34,
    earthDamage: 2,
    evasion: 8,
    attackRating: 15,
    attackSpeed: 1.0,
    gold: 14,
    xp: 13,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: '🔥',
  },
  {
    name: 'Thunderwing',
    element: 'air',
    image: '/enemies/thunderwing.jpg',
    tier: tier,
    damage: 2,
    airDamage: 4,
    fireResistance: 10,
    airResistance: 20,
    coldResistance: 5,
    earthResistance: 5,
    lightningResistance: 15,
    waterResistance: 5,
    attackSpeed: 1.3,
    life: 28,
    armor: 7,
    evasion: 9,
    attackRating: 14,
    gold: 12,
    xp: 11,
    materialDropWeights: {},
    tags: ['volcano', 'air'],
  },
];
