import { t } from '../../i18n.js';
const BASE = import.meta.env.VITE_BASE_PATH;
const DROP_ICONS = {
  item_drop: `<img src="${BASE}/icons/armor.svg" class="icon" alt="item drop"/>`,
  material_drop: `<img src="${BASE}/icons/armor-upgrade-stone.svg" class="icon" alt="material drop"/>`,
};
// Item and material drop quests
export const DROP_QUESTS = [
  // Item Drop Quests
  {
    id: 'itemdrop_5',
    category: 'drops',
    title: 'First Find',
    description: t('Find 5 items.'),
    type: 'item_drop',
    target: 5,
    reward: { item: { rarity: 'rare', type: 'random', tier: 2 } },
  },
  {
    id: 'itemdrop_25',
    category: 'drops',
    title: 'Treasure Hunter',
    description: t('Find 25 items.'),
    type: 'item_drop',
    target: 25,
    reward: { item: { rarity: 'unique', type: 'random', tier: 2 } },
  },
  {
    id: 'itemdrop_60',
    category: 'drops',
    title: 'Loot Collector',
    description: t('Find 60 items.'),
    type: 'item_drop',
    target: 60,
    reward: { item: { rarity: 'unique', type: 'random', tier: 3 } },
  },
  {
    id: 'itemdrop_150',
    category: 'drops',
    title: 'Relic Seeker',
    description: t('Find 150 items.'),
    type: 'item_drop',
    target: 150,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 3 } },
  },
  {
    id: 'itemdrop_300',
    category: 'drops',
    title: 'Epic Hoarder',
    description: t('Find 300 items.'),
    type: 'item_drop',
    target: 300,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 4 } },
  },
  {
    id: 'itemdrop_750',
    category: 'drops',
    title: 'Mythic Collector',
    description: t('Find 750 items.'),
    type: 'item_drop',
    target: 750,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 5 } },
  },
  {
    id: 'itemdrop_1500',
    category: 'drops',
    title: 'Ultimate Hoarder',
    description: t('Find 1,500 items.'),
    type: 'item_drop',
    target: 1500,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 5 } },
  },
  {
    id: 'itemdrop_3000',
    category: 'drops',
    title: 'Worldly Collector',
    description: t('Find 3,000 items.'),
    type: 'item_drop',
    target: 3000,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 6 } },
  },
  {
    id: 'itemdrop_6000',
    category: 'drops',
    title: 'Infinite Vault',
    description: t('Find 6,000 items.'),
    type: 'item_drop',
    target: 6000,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 7 } },
  },
  // Material Drop Quests
  {
    id: 'matdrop_5',
    category: 'drops',
    title: 'First Material',
    description: t('Collect 5 materials.'),
    type: 'material_drop',
    target: 5,
    reward: { item: { rarity: 'rare', type: 'random', tier: 1 } },
  },
  {
    id: 'matdrop_25',
    category: 'drops',
    title: 'Material Gatherer',
    description: t('Collect 25 materials.'),
    type: 'material_drop',
    target: 25,
    reward: { item: { rarity: 'unique', type: 'random', tier: 1 } },
  },
  {
    id: 'matdrop_60',
    category: 'drops',
    title: 'Resourceful',
    description: t('Collect 60 materials.'),
    type: 'material_drop',
    target: 60,
    reward: { item: { rarity: 'unique', type: 'random', tier: 2 } },
  },
  {
    id: 'matdrop_150',
    category: 'drops',
    title: 'Materialist',
    description: t('Collect 150 materials.'),
    type: 'material_drop',
    target: 150,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 3 } },
  },
  {
    id: 'matdrop_300',
    category: 'drops',
    title: 'Legendary Gatherer',
    description: t('Collect 300 materials.'),
    type: 'material_drop',
    target: 300,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 3 } },
  },
  {
    id: 'matdrop_750',
    category: 'drops',
    title: 'Mythic Prospector',
    description: t('Collect 750 materials.'),
    type: 'material_drop',
    target: 750,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 3 } },
  },
  {
    id: 'matdrop_1500',
    category: 'drops',
    title: 'Master Prospector',
    description: t('Collect 1,500 materials.'),
    type: 'material_drop',
    target: 1500,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 4 } },
  },
  {
    id: 'matdrop_3000',
    category: 'drops',
    title: 'Worldly Prospector',
    description: t('Collect 3,000 materials.'),
    type: 'material_drop',
    target: 3000,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 5 } },
  },
  {
    id: 'matdrop_6000',
    category: 'drops',
    title: 'Infinite Prospector',
    description: t('Collect 6,000 materials.'),
    type: 'material_drop',
    target: 6000,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 6 } },
  },
].map((q) => ({ ...q, icon: DROP_ICONS[q.type] }));
