import { t } from '../../i18n.js';
const BASE = import.meta.env.VITE_BASE_PATH;
// Kill quests
export const KILL_QUESTS = [
  {
    id: 'kill10',
    category: 'kills',
    title: 'First Blood',
    description: t('Defeat 10 enemies.'),
    type: 'kill',
    target: 10,
    reward: { gold: 500, crystals: 1, item: { rarity: 'rare', type: 'random', tier: 1 } },
    icon: `<img src="${BASE}/icons/sword.svg" class="icon" alt="kills"/>`,
  },
  {
    id: 'kill50',
    category: 'kills',
    title: 'Warrior',
    description: t('Defeat 50 enemies.'),
    type: 'kill',
    target: 50,
    reward: { gold: 1500, crystals: 2 },
    icon: `<img src="${BASE}/icons/sword.svg" class="icon" alt="kills"/>`,
  },
  {
    id: 'kill250',
    category: 'kills',
    title: 'Destroyer',
    description: t('Defeat 250 enemies.'),
    type: 'kill',
    target: 250,
    reward: { gold: 4000, item: { rarity: 'rare', type: 'random', tier: 1 } },
    icon: `<img src="${BASE}/icons/lightning.svg" class="icon" alt="crit"/>`,
  },
  {
    id: 'kill1000',
    category: 'kills',
    title: 'Massacre',
    description: t('Defeat 1000 enemies.'),
    type: 'kill',
    target: 1000,
    reward: { gold: 10000, crystals: 1 },
    icon: `<img src="${BASE}/icons/skull.svg" class="icon" alt="skull"/>`,
  },
  {
    id: 'kill2500',
    category: 'kills',
    title: 'Harbinger',
    description: t('Defeat 2500 enemies.'),
    type: 'kill',
    target: 2500,
    reward: { gold: 30000, crystals: 4 },
    icon: `<img src="${BASE}/icons/skull.svg" class="icon" alt="skull"/>`,
  },
  {
    id: 'kill5000',
    category: 'kills',
    title: 'Death Incarnate',
    description: t('Defeat 5000 enemies.'),
    type: 'kill',
    target: 5000,
    reward: { gold: 60000, crystals: 2 },
    icon: `<img src="${BASE}/icons/skull.svg" class="icon" alt="skull"/>`,
  },
  {
    id: 'kill10000',
    category: 'kills',
    title: 'Apocalypse',
    description: t('Defeat 10000 enemies.'),
    type: 'kill',
    target: 10000,
    reward: { gold: 100000, crystals: 3 },
    icon: `<img src="${BASE}/icons/skull.svg" class="icon" alt="skull"/>`,
  },
  {
    id: 'kill25000',
    category: 'kills',
    title: 'World Ender',
    description: t('Defeat 25000 enemies.'),
    type: 'kill',
    target: 25000,
    reward: { gold: 200000, crystals: 5 },
    icon: `<img src="${BASE}/icons/earth.svg" class="icon" alt="earth"/>`,
  },
  {
    id: 'kill50000',
    category: 'kills',
    title: 'Extinction Event',
    description: t('Defeat 50000 enemies.'),
    type: 'kill',
    target: 50000,
    reward: { gold: 400000, crystals: 8 },
    icon: `<img src="${BASE}/icons/earth.svg" class="icon" alt="earth"/>`,
  },
  {
    id: 'kill100000',
    category: 'kills',
    title: 'Universal Threat',
    description: t('Defeat 100000 enemies.'),
    type: 'kill',
    target: 100000,
    reward: { gold: 700000, crystals: 12 },
    icon: `<img src="${BASE}/icons/moon.svg" class="icon" alt="night"/>`,
  },
  {
    id: 'kill250000',
    category: 'kills',
    title: 'Cosmic Terror',
    description: t('Defeat 250000 enemies.'),
    type: 'kill',
    target: 250000,
    reward: { gold: 2000000, crystals: 20 },
    icon: `<img src="${BASE}/icons/moon.svg" class="icon" alt="night"/>`,
  },
  {
    id: 'kill500000',
    category: 'kills',
    title: 'Reality Breaker',
    description: t('Defeat 500000 enemies.'),
    type: 'kill',
    target: 500000,
    reward: { gold: 6000000, crystals: 30 },
    icon: `<img src="${BASE}/icons/star.svg" class="icon" alt="star"/>`,
  },
  {
    id: 'kill1000000',
    category: 'kills',
    title: 'Infinite Void',
    description: t('Defeat 1000000 enemies.'),
    type: 'kill',
    target: 1000000,
    reward: { gold: 15000000, crystals: 50 },
    icon: `<img src="${BASE}/icons/star.svg" class="icon" alt="star"/>`,
  },
  {
    id: 'kill2500000',
    category: 'kills',
    title: 'Endless Slaughter',
    description: t('Defeat 2500000 enemies.'),
    type: 'kill',
    target: 2500000,
    reward: { gold: 25000000, crystals: 70 },
    icon: `<img src="${BASE}/icons/star.svg" class="icon" alt="star"/>`,
  },
  {
    id: 'kill5000000',
    category: 'kills',
    title: 'Catastrophic Annihilator',
    description: t('Defeat 5000000 enemies.'),
    type: 'kill',
    target: 5000000,
    reward: { gold: 60000000, crystals: 100 },
    icon: `<img src="${BASE}/icons/star.svg" class="icon" alt="star"/>`,
  },
  {
    id: 'kill10000000',
    category: 'kills',
    title: 'Infinite Destroyer',
    description: t('Defeat 10000000 enemies.'),
    type: 'kill',
    target: 10000000,
    reward: { gold: 150000000, crystals: 200 },
    icon: `<img src="${BASE}/icons/star.svg" class="icon" alt="orbit"/>`,
  },
];
