// Progression quests
export const PROGRESSION_QUESTS = [
  // Level
  {
    id: 'level_5',
    category: 'progression',
    title: 'Rookie',
    description: 'Reach level 5.',
    type: 'level',
    target: 5,
    reward: { gold: 200, crystals: 1, item: { rarity: 'rare', type: 'random', tier: 1 } },
    icon: '🧙',
  },
  {
    id: 'level_10',
    category: 'progression',
    title: 'Novice Adventurer',
    description: 'Reach level 10.',
    type: 'level',
    target: 10,
    reward: { gold: 500, crystals: 1, item: { rarity: 'rare', type: 'random', tier: 1 } },
    icon: '🧙',
  },
  {
    id: 'level_25',
    category: 'progression',
    title: 'Experienced Fighter',
    description: 'Reach level 25.',
    type: 'level',
    target: 25,
    reward: { gold: 1000, crystals: 1 },
    icon: '🦸',
  },
  {
    id: 'level_50',
    category: 'progression',
    title: 'Seasoned Hero',
    description: 'Reach level 50.',
    type: 'level',
    target: 50,
    reward: { gold: 2000, crystals: 2 },
    icon: '🦸',
  },
  {
    id: 'level_75',
    category: 'progression',
    title: 'Veteran Warrior',
    description: 'Reach level 75.',
    type: 'level',
    target: 75,
    reward: { gold: 5000, crystals: 2 },
    icon: '🦸',
  },
  {
    id: 'level_100',
    category: 'progression',
    title: 'Elite Champion',
    description: 'Reach level 100.',
    type: 'level',
    target: 100,
    reward: { gold: 10000, crystals: 3 },
    icon: '⭐',
  },
  {
    id: 'level_150',
    category: 'progression',
    title: 'Master Hero',
    description: 'Reach level 150.',
    type: 'level',
    target: 150,
    reward: { gold: 20000, crystals: 5 },
    icon: '⭐',
  },
  {
    id: 'level_200',
    category: 'progression',
    title: 'Legendary Being',
    description: 'Reach level 200.',
    type: 'level',
    target: 200,
    reward: { gold: 40000, crystals: 8 },
    icon: '🌟',
  },
  {
    id: 'level_300',
    category: 'progression',
    title: 'Transcendent',
    description: 'Reach level 300.',
    type: 'level',
    target: 300,
    reward: { gold: 80000, crystals: 12 },
    icon: '🌟',
  },
  {
    id: 'level_500',
    category: 'progression',
    title: 'Ascended One',
    description: 'Reach level 500.',
    type: 'level',
    target: 500,
    reward: { gold: 150000, crystals: 20 },
    icon: '✨',
  },
  {
    id: 'level_750',
    category: 'progression',
    title: 'Divine Hero',
    description: 'Reach level 750.',
    type: 'level',
    target: 750,
    reward: { gold: 300000, crystals: 30 },
    icon: '✨',
  },
  {
    id: 'level_1000',
    category: 'progression',
    title: 'Mythic Legend',
    description: 'Reach level 1000.',
    type: 'level',
    target: 1000,
    reward: { gold: 600000, crystals: 50 },
    icon: '💫',
  },
  // Damage
  {
    id: 'damage_1000',
    category: 'progression',
    title: 'Big Hit',
    description: 'Deal 1,000 damage in a single hit.',
    type: 'damage',
    target: 1000,
    reward: { crystals: 1 },
    icon: '💥',
  },
  {
    id: 'damage_10000',
    category: 'progression',
    title: 'Devastating Strike',
    description: 'Deal 10,000 damage in a single hit.',
    type: 'damage',
    target: 10000,
    reward: { crystals: 2 },
    icon: '💥',
  },
  {
    id: 'damage_100000',
    category: 'progression',
    title: 'Cataclysmic Blow',
    description: 'Deal 100,000 damage in a single hit.',
    type: 'damage',
    target: 100000,
    reward: { crystals: 3 },
    icon: '💢',
  },
  {
    id: 'damage_1000000',
    category: 'progression',
    title: 'Reality Shattering',
    description: 'Deal 1,000,000 damage in a single hit.',
    type: 'damage',
    target: 1000000,
    reward: { crystals: 5 },
    icon: '💢',
  },
  {
    id: 'damage_5000000',
    category: 'progression',
    title: 'Dimensional Ruin',
    description: 'Deal 5,000,000 damage in a single hit.',
    type: 'damage',
    target: 5000000,
    reward: { crystals: 8 },
    icon: '💥',
  },
  {
    id: 'damage_10000000',
    category: 'progression',
    title: 'Endless Destruction',
    description: 'Deal 10,000,000 damage in a single hit.',
    type: 'damage',
    target: 10000000,
    reward: { crystals: 12 },
    icon: '💥',
  },
];
