import { t } from '../../i18n.js';
// Rarity kill quests
export const RARITY_QUESTS = [
  // Rare
  {
    id: 'kill_rare_10',
    category: 'rarity',
    title: 'Rare Hunter',
    description: t('Defeat 10 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 10,
    reward: { gold: 500, crystals: 1, item: { rarity: 'rare', type: 'random', tier: 1 } },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_50',
    category: 'rarity',
    title: 'Rare Specialist',
    description: t('Defeat 50 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 50,
    reward: { gold: 1500, crystals: 1 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_200',
    category: 'rarity',
    title: 'Rare Exterminator',
    description: t('Defeat 200 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 200,
    reward: { gold: 4000, crystals: 2 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_600',
    category: 'rarity',
    title: 'Rare Nemesis',
    description: t('Defeat 600 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 600,
    reward: { gold: 12000, crystals: 3 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_1500',
    category: 'rarity',
    title: 'Rare Apocalypse',
    description: t('Defeat 1500 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 1500,
    reward: { gold: 30000, crystals: 5 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_4000',
    category: 'rarity',
    title: 'Rare Cataclysm',
    description: t('Defeat 4000 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 4000,
    reward: { gold: 90000, crystals: 8 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_15000',
    category: 'rarity',
    title: 'Rare Extinction',
    description: t('Defeat 15000 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 15000,
    reward: { gold: 350000, crystals: 15 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  {
    id: 'kill_rare_30000',
    category: 'rarity',
    title: 'Rare Obliteration',
    description: t('Defeat 30000 rare enemies.'),
    type: 'kill_rarity',
    rarity: 'rare',
    target: 30000,
    reward: { gold: 1200000, crystals: 25 },
    icon: '<i class="mdi mdi-circle" style="color:#2196f3"></i>',
  },
  // Epic
  {
    id: 'kill_epic_5',
    category: 'rarity',
    title: 'Epic Slayer',
    description: t('Defeat 5 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 5,
    reward: { gold: 1200, crystals: 1, item: { rarity: 'unique', type: 'random', tier: 1 } },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_30',
    category: 'rarity',
    title: 'Epic Destroyer',
    description: t('Defeat 30 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 30,
    reward: { gold: 6000, crystals: 2 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_75',
    category: 'rarity',
    title: 'Epic Vanquisher',
    description: t('Defeat 75 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 75,
    reward: { gold: 15000, crystals: 3 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_200',
    category: 'rarity',
    title: 'Epic Bane',
    description: t('Defeat 200 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 200,
    reward: { gold: 40000, crystals: 5 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_500',
    category: 'rarity',
    title: 'Epic Annihilator',
    description: t('Defeat 500 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 500,
    reward: { gold: 120000, crystals: 8 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_1200',
    category: 'rarity',
    title: 'Epic Obliterator',
    description: t('Defeat 1200 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 1200,
    reward: { gold: 350000, crystals: 15 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_4000',
    category: 'rarity',
    title: 'Epic Extinction',
    description: t('Defeat 4000 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 4000,
    reward: { gold: 900000, crystals: 30 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  {
    id: 'kill_epic_8000',
    category: 'rarity',
    title: 'Epic Cataclysm',
    description: t('Defeat 8000 epic enemies.'),
    type: 'kill_rarity',
    rarity: 'epic',
    target: 8000,
    reward: { gold: 2500000, crystals: 40 },
    icon: '<i class="mdi mdi-circle" style="color:#9c27b0"></i>',
  },
  // Legendary
  {
    id: 'kill_legendary_3',
    category: 'rarity',
    title: 'Legendary Conqueror',
    description: t('Defeat 3 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 3,
    reward: { gold: 3500, crystals: 2 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_15',
    category: 'rarity',
    title: 'Legendary Hunter',
    description: t('Defeat 15 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 15,
    reward: { gold: 20000, crystals: 5, item: { rarity: 'legendary', type: 'random', tier: 1 } },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_50',
    category: 'rarity',
    title: 'Legendary Slayer',
    description: t('Defeat 50 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 50,
    reward: { gold: 70000, crystals: 8 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_120',
    category: 'rarity',
    title: 'Legendary Destroyer',
    description: t('Defeat 120 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 120,
    reward: { gold: 180000, crystals: 12 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_400',
    category: 'rarity',
    title: 'Legendary Nightmare',
    description: t('Defeat 400 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 400,
    reward: { gold: 600000, crystals: 20 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_900',
    category: 'rarity',
    title: 'Legendary Oblivion',
    description: t('Defeat 900 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 900,
    reward: { gold: 1500000, crystals: 35 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_2400',
    category: 'rarity',
    title: 'Legendary Extinction',
    description: t('Defeat 2400 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 2400,
    reward: { gold: 4000000, crystals: 60 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  {
    id: 'kill_legendary_5000',
    category: 'rarity',
    title: 'Legendary Apocalypse',
    description: t('Defeat 5000 legendary enemies.'),
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 5000,
    reward: { gold: 12000000, crystals: 90 },
    icon: '<i class="mdi mdi-circle" style="color:#ff9800"></i>',
  },
  // Mythic
  {
    id: 'kill_mythic_1',
    category: 'rarity',
    title: 'Mythic Bane',
    description: t('Defeat 1 mythic enemy.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1,
    reward: { gold: 5000, crystals: 3 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_8',
    category: 'rarity',
    title: 'Mythic Slayer',
    description: t('Defeat 8 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 8,
    reward: { gold: 35000, crystals: 8 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_38',
    category: 'rarity',
    title: 'Mythic Hunter',
    description: t('Defeat 38 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 38,
    reward: { gold: 120000, crystals: 15 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_80',
    category: 'rarity',
    title: 'Mythic Destroyer',
    description: t('Defeat 80 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 80,
    reward: { gold: 350000, crystals: 25, item: { rarity: 'mythic', type: 'random', tier: 1 } },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_200',
    category: 'rarity',
    title: 'Mythic Nightmare',
    description: t('Defeat 200 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 200,
    reward: { gold: 900000, crystals: 40 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_450',
    category: 'rarity',
    title: 'Mythic Oblivion',
    description: t('Defeat 450 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 450,
    reward: { gold: 2500000, crystals: 60 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_1200',
    category: 'rarity',
    title: 'Mythic Extinction',
    description: t('Defeat 1200 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1200,
    reward: { gold: 7000000, crystals: 100 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
  {
    id: 'kill_mythic_3000',
    category: 'rarity',
    title: 'Mythic Cataclysm',
    description: t('Defeat 3000 mythic enemies.'),
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 3000,
    reward: { gold: 20000000, crystals: 150 },
    icon: '<i class="mdi mdi-circle" style="color:#f44336"></i>',
  },
];
