import { tp } from '../../i18n.js';
const BASE = import.meta.env.VITE_BASE_PATH;
const RARITY_ICONS = {
  rare: `<img src="${BASE}/icons/star.svg" class="icon" alt="rare"/>`,
  epic: `<img src="${BASE}/icons/moon.svg" class="icon" alt="epic"/>`,
  legendary: `<img src="${BASE}/icons/earth.svg" class="icon" alt="legendary"/>`,
  mythic: `<img src="${BASE}/icons/fire.svg" class="icon" alt="mythic"/>`,
};
// Rarity kill quests
export const RARITY_QUESTS = [
  // Rare
  {
    id: 'kill_rare_10',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 10 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 10 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 10,
    reward: { gold: 500, crystals: 1, item: { rarity: 'rare', type: 'random', tier: 1 } },
  },
  {
    id: 'kill_rare_50',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 50 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 50 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 50,
    reward: { gold: 1500, crystals: 1 },
  },
  {
    id: 'kill_rare_200',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 200 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 200 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 200,
    reward: { gold: 4000, crystals: 2 },
  },
  {
    id: 'kill_rare_600',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 600 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 600 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 600,
    reward: { gold: 12000, crystals: 3 },
  },
  {
    id: 'kill_rare_1500',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 1500 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 1500 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 1500,
    reward: { gold: 30000, crystals: 5 },
  },
  {
    id: 'kill_rare_4000',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 4000 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 4000 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 4000,
    reward: { gold: 90000, crystals: 8 },
  },
  {
    id: 'kill_rare_15000',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 15000 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 15000 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 15000,
    reward: { gold: 350000, crystals: 15 },
  },
  {
    id: 'kill_rare_30000',
    category: 'rarity',
    get title() { return tp('Defeat {count} rare enemies.', { count: 30000 }); },
    get description() { return tp('Defeat {count} rare enemies.', { count: 30000 }); },
    type: 'kill_rarity',
    rarity: 'rare',
    target: 30000,
    reward: { gold: 1200000, crystals: 25 },
  },
  // Epic
  {
    id: 'kill_epic_5',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 5 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 5 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 5,
    reward: { gold: 1200, crystals: 1, item: { rarity: 'epic', type: 'random', tier: 1 } },
  },
  {
    id: 'kill_epic_30',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 30 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 30 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 30,
    reward: { gold: 6000, crystals: 2 },
  },
  {
    id: 'kill_epic_75',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 75 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 75 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 75,
    reward: { gold: 15000, crystals: 3 },
  },
  {
    id: 'kill_epic_200',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 200 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 200 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 200,
    reward: { gold: 40000, crystals: 5 },
  },
  {
    id: 'kill_epic_500',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 500 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 500 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 500,
    reward: { gold: 120000, crystals: 8 },
  },
  {
    id: 'kill_epic_1200',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 1200 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 1200 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 1200,
    reward: { gold: 350000, crystals: 15 },
  },
  {
    id: 'kill_epic_4000',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 4000 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 4000 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 4000,
    reward: { gold: 900000, crystals: 30 },
  },
  {
    id: 'kill_epic_8000',
    category: 'rarity',
    get title() { return tp('Defeat {count} epic enemies.', { count: 8000 }); },
    get description() { return tp('Defeat {count} epic enemies.', { count: 8000 }); },
    type: 'kill_rarity',
    rarity: 'epic',
    target: 8000,
    reward: { gold: 2500000, crystals: 40 },
  },
  // Legendary
  {
    id: 'kill_legendary_3',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 3 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 3 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 3,
    reward: { gold: 3500, crystals: 2 },
  },
  {
    id: 'kill_legendary_15',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 15 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 15 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 15,
    reward: { gold: 20000, crystals: 5, item: { rarity: 'legendary', type: 'random', tier: 1 } },
  },
  {
    id: 'kill_legendary_50',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 50 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 50 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 50,
    reward: { gold: 70000, crystals: 8 },
  },
  {
    id: 'kill_legendary_120',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 120 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 120 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 120,
    reward: { gold: 180000, crystals: 12 },
  },
  {
    id: 'kill_legendary_400',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 400 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 400 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 400,
    reward: { gold: 600000, crystals: 20 },
  },
  {
    id: 'kill_legendary_900',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 900 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 900 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 900,
    reward: { gold: 1500000, crystals: 35 },
  },
  {
    id: 'kill_legendary_2400',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 2400 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 2400 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 2400,
    reward: { gold: 4000000, crystals: 60 },
  },
  {
    id: 'kill_legendary_5000',
    category: 'rarity',
    get title() { return tp('Defeat {count} legendary enemies.', { count: 5000 }); },
    get description() { return tp('Defeat {count} legendary enemies.', { count: 5000 }); },
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 5000,
    reward: { gold: 12000000, crystals: 90 },
  },
  // Mythic
  {
    id: 'kill_mythic_1',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 1 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 1 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1,
    reward: { gold: 5000, crystals: 3 },
  },
  {
    id: 'kill_mythic_8',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 8 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 8 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 8,
    reward: { gold: 35000, crystals: 8 },
  },
  {
    id: 'kill_mythic_38',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 38 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 38 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 38,
    reward: { gold: 120000, crystals: 15 },
  },
  {
    id: 'kill_mythic_80',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 80 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 80 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 80,
    reward: { gold: 350000, crystals: 25, item: { rarity: 'mythic', type: 'random', tier: 1 } },
  },
  {
    id: 'kill_mythic_200',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 200 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 200 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 200,
    reward: { gold: 900000, crystals: 40 },
  },
  {
    id: 'kill_mythic_450',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 450 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 450 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 450,
    reward: { gold: 2500000, crystals: 60 },
  },
  {
    id: 'kill_mythic_1200',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 1200 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 1200 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1200,
    reward: { gold: 7000000, crystals: 100 },
  },
  {
    id: 'kill_mythic_3000',
    category: 'rarity',
    get title() { return tp('Defeat {count} mythic enemies.', { count: 3000 }); },
    get description() { return tp('Defeat {count} mythic enemies.', { count: 3000 }); },
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 3000,
    reward: { gold: 20000000, crystals: 150 },
  },
].map((q) => {
  const quest = { icon: RARITY_ICONS[q.rarity] };
  Object.defineProperties(quest, Object.getOwnPropertyDescriptors(q));
  return quest;
});
