// Rarity kill quests
export const RARITY_QUESTS = [
  // Rare
  {
    id: 'kill_rare_10',
    category: 'rarity',
    title: 'Rare Hunter',
    description: 'Defeat 10 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 10,
    reward: { gold: 500, crystals: 1, item: { rarity: 'rare', type: 'random', tier: 1 } },
    icon: '🔵',
  },
  {
    id: 'kill_rare_50',
    category: 'rarity',
    title: 'Rare Specialist',
    description: 'Defeat 50 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 50,
    reward: { gold: 1500, crystals: 1 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_200',
    category: 'rarity',
    title: 'Rare Exterminator',
    description: 'Defeat 200 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 200,
    reward: { gold: 4000, crystals: 2 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_600',
    category: 'rarity',
    title: 'Rare Nemesis',
    description: 'Defeat 600 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 600,
    reward: { gold: 12000, crystals: 3 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_1500',
    category: 'rarity',
    title: 'Rare Apocalypse',
    description: 'Defeat 1500 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 1500,
    reward: { gold: 30000, crystals: 5 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_4000',
    category: 'rarity',
    title: 'Rare Cataclysm',
    description: 'Defeat 4000 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 4000,
    reward: { gold: 90000, crystals: 8 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_15000',
    category: 'rarity',
    title: 'Rare Extinction',
    description: 'Defeat 15000 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 15000,
    reward: { gold: 350000, crystals: 15 },
    icon: '🔵',
  },
  // Epic
  {
    id: 'kill_epic_5',
    category: 'rarity',
    title: 'Epic Slayer',
    description: 'Defeat 5 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 5,
    reward: { gold: 1200, crystals: 1, item: { rarity: 'unique', type: 'random', tier: 1 } },
    icon: '🟣',
  },
  {
    id: 'kill_epic_30',
    category: 'rarity',
    title: 'Epic Destroyer',
    description: 'Defeat 30 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 30,
    reward: { gold: 6000, crystals: 2 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_75',
    category: 'rarity',
    title: 'Epic Vanquisher',
    description: 'Defeat 75 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 75,
    reward: { gold: 15000, crystals: 3 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_200',
    category: 'rarity',
    title: 'Epic Bane',
    description: 'Defeat 200 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 200,
    reward: { gold: 40000, crystals: 5 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_500',
    category: 'rarity',
    title: 'Epic Annihilator',
    description: 'Defeat 500 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 500,
    reward: { gold: 120000, crystals: 8 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_1200',
    category: 'rarity',
    title: 'Epic Obliterator',
    description: 'Defeat 1200 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 1200,
    reward: { gold: 350000, crystals: 15 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_4000',
    category: 'rarity',
    title: 'Epic Extinction',
    description: 'Defeat 4000 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 4000,
    reward: { gold: 900000, crystals: 30 },
    icon: '🟣',
  },
  // Legendary
  {
    id: 'kill_legendary_3',
    category: 'rarity',
    title: 'Legendary Conqueror',
    description: 'Defeat 3 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 3,
    reward: { gold: 3500, crystals: 2 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_15',
    category: 'rarity',
    title: 'Legendary Hunter',
    description: 'Defeat 15 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 15,
    reward: { gold: 20000, crystals: 5, item: { rarity: 'legendary', type: 'random', tier: 1 } },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_50',
    category: 'rarity',
    title: 'Legendary Slayer',
    description: 'Defeat 50 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 50,
    reward: { gold: 70000, crystals: 8 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_120',
    category: 'rarity',
    title: 'Legendary Destroyer',
    description: 'Defeat 120 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 120,
    reward: { gold: 180000, crystals: 12 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_400',
    category: 'rarity',
    title: 'Legendary Nightmare',
    description: 'Defeat 400 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 400,
    reward: { gold: 600000, crystals: 20 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_900',
    category: 'rarity',
    title: 'Legendary Oblivion',
    description: 'Defeat 900 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 900,
    reward: { gold: 1500000, crystals: 35 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_2400',
    category: 'rarity',
    title: 'Legendary Extinction',
    description: 'Defeat 2400 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 2400,
    reward: { gold: 4000000, crystals: 60 },
    icon: '🟠',
  },
  // Mythic
  {
    id: 'kill_mythic_1',
    category: 'rarity',
    title: 'Mythic Bane',
    description: 'Defeat 1 mythic enemy.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1,
    reward: { gold: 5000, crystals: 3 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_8',
    category: 'rarity',
    title: 'Mythic Slayer',
    description: 'Defeat 8 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 8,
    reward: { gold: 35000, crystals: 8 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_38',
    category: 'rarity',
    title: 'Mythic Hunter',
    description: 'Defeat 38 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 38,
    reward: { gold: 120000, crystals: 15 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_80',
    category: 'rarity',
    title: 'Mythic Destroyer',
    description: 'Defeat 80 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 80,
    reward: { gold: 350000, crystals: 25, item: { rarity: 'mythic', type: 'random', tier: 1 } },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_200',
    category: 'rarity',
    title: 'Mythic Nightmare',
    description: 'Defeat 200 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 200,
    reward: { gold: 900000, crystals: 40 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_450',
    category: 'rarity',
    title: 'Mythic Oblivion',
    description: 'Defeat 450 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 450,
    reward: { gold: 2500000, crystals: 60 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_1200',
    category: 'rarity',
    title: 'Mythic Extinction',
    description: 'Defeat 1200 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1200,
    reward: { gold: 7000000, crystals: 100 },
    icon: '🔴',
  },
];
