import { tp } from '../../i18n.js';
const BASE = import.meta.env.VITE_BASE_PATH;
const RESOURCE_ICONS = {
  totalGoldEarned: `<img src="${BASE}/icons/gold-coin.svg" class="icon" alt="gold"/>`,
  crystals: `<img src="${BASE}/icons/crystal.svg" class="icon" alt="crystal"/>`,
};
// Resource quests
export const RESOURCE_QUESTS = [
  {
    id: 'gold_1000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '1,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '1,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1000,
    reward: { gold: 500 },
  },
  {
    id: 'gold_5000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '5,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '5,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 5000,
    reward: { crystals: 1 },
  },
  {
    id: 'gold_15000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '15,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '15,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 15000,
    reward: { crystals: 2 },
  },
  {
    id: 'gold_50000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '50,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '50,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 50000,
    reward: { crystals: 3 },
  },
  {
    id: 'gold_150000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '150,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '150,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 150000,
    reward: { crystals: 4 },
  },
  {
    id: 'gold_500000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '500,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '500,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 500000,
    reward: { crystals: 5 },
  },
  {
    id: 'gold_1500000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '1,500,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '1,500,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1500000,
    reward: { crystals: 6 },
  },
  {
    id: 'gold_5000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '5,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '5,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 5000000,
    reward: { crystals: 7 },
  },
  {
    id: 'gold_15000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '15,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '15,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 15000000,
    reward: { crystals: 8 },
  },
  {
    id: 'gold_50000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '50,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '50,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 50000000,
    reward: { crystals: 12 },
  },
  {
    id: 'gold_100000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '100,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '100,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 100000000,
    reward: { crystals: 20 },
  },
  {
    id: 'gold_250000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '250,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '250,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 250000000,
    reward: { crystals: 30 },
  },
  {
    id: 'gold_500000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '500,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '500,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 500000000,
    reward: { crystals: 40 },
  },
  {
    id: 'gold_1000000000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} gold.', { count: '1,000,000,000' }); },
    get description() { return tp('Earn a total of {count} gold.', { count: '1,000,000,000' }); },
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1000000000,
    reward: { crystals: 60 },
  },
  // Crystals
  {
    id: 'crystals_5',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 5 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 5 }); },
    type: 'resource',
    resource: 'crystals',
    target: 5,
    reward: { gold: 1000 },
  },
  {
    id: 'crystals_10',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 10 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 10 }); },
    type: 'resource',
    resource: 'crystals',
    target: 10,
    reward: { gold: 2000 },
  },
  {
    id: 'crystals_25',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 25 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 25 }); },
    type: 'resource',
    resource: 'crystals',
    target: 25,
    reward: { gold: 5000 },
  },
  {
    id: 'crystals_50',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 50 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 50 }); },
    type: 'resource',
    resource: 'crystals',
    target: 50,
    reward: { gold: 10000 },
  },
  {
    id: 'crystals_100',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 100 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 100 }); },
    type: 'resource',
    resource: 'crystals',
    target: 100,
    reward: { gold: 25000 },
  },
  {
    id: 'crystals_250',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 250 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 250 }); },
    type: 'resource',
    resource: 'crystals',
    target: 250,
    reward: { gold: 50000 },
  },
  {
    id: 'crystals_500',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: 500 }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: 500 }); },
    type: 'resource',
    resource: 'crystals',
    target: 500,
    reward: { gold: 100000 },
  },
  {
    id: 'crystals_1000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: '1,000' }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: '1,000' }); },
    type: 'resource',
    resource: 'crystals',
    target: 1000,
    reward: { gold: 250000 },
  },
  {
    id: 'crystals_2000',
    category: 'resources',
    get title() { return tp('Earn a total of {count} crystals.', { count: '2,000' }); },
    get description() { return tp('Earn a total of {count} crystals.', { count: '2,000' }); },
    type: 'resource',
    resource: 'crystals',
    target: 2000,
    reward: { gold: 500000 },
  },
].map((q) => {
  const quest = { icon: RESOURCE_ICONS[q.resource] };
  Object.defineProperties(quest, Object.getOwnPropertyDescriptors(q));
  return quest;
});
