import { t } from '../../i18n.js';
// Resource quests
export const RESOURCE_QUESTS = [
  {
    id: 'gold_1000',
    category: 'resources',
    title: 'Pocket Change',
    description: t('Earn a total of 1,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1000,
    reward: { gold: 500 },
    icon: '💰',
  },
  {
    id: 'gold_5000',
    category: 'resources',
    title: 'Small Fortune',
    description: t('Earn a total of 5,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 5000,
    reward: { crystals: 1 },
    icon: '💰',
  },
  {
    id: 'gold_15000',
    category: 'resources',
    title: 'Gold Hoarder',
    description: t('Earn a total of 15,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 15000,
    reward: { crystals: 1 },
    icon: '💰',
  },
  {
    id: 'gold_50000',
    category: 'resources',
    title: 'Wealthy Adventurer',
    description: t('Earn a total of 50,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 50000,
    reward: { crystals: 1 },
    icon: '💰',
  },
  {
    id: 'gold_150000',
    category: 'resources',
    title: 'Rich Merchant',
    description: t('Earn a total of 150,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 150000,
    reward: { crystals: 2 },
    icon: '💰',
  },
  {
    id: 'gold_500000',
    category: 'resources',
    title: 'Treasure Tycoon',
    description: t('Earn a total of 500,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 500000,
    reward: { crystals: 2 },
    icon: '🏆',
  },
  {
    id: 'gold_1500000',
    category: 'resources',
    title: 'Gold Baron',
    description: t('Earn a total of 1,500,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1500000,
    reward: { crystals: 3 },
    icon: '🏆',
  },
  {
    id: 'gold_5000000',
    category: 'resources',
    title: 'Millionaire',
    description: t('Earn a total of 5,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 5000000,
    reward: { crystals: 5 },
    icon: '🏆',
  },
  {
    id: 'gold_15000000',
    category: 'resources',
    title: 'Gold Baron',
    description: t('Earn a total of 15,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 15000000,
    reward: { crystals: 8 },
    icon: '🏆',
  },
  {
    id: 'gold_50000000',
    category: 'resources',
    title: 'Treasure God',
    description: t('Earn a total of 50,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 50000000,
    reward: { crystals: 12 },
    icon: '👑',
  },
  {
    id: 'gold_100000000',
    category: 'resources',
    title: 'Midas Touch',
    description: t('Earn a total of 100,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 100000000,
    reward: { crystals: 20 },
    icon: '👑',
  },
  {
    id: 'gold_250000000',
    category: 'resources',
    title: 'Infinite Wealth',
    description: t('Earn a total of 250,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 250000000,
    reward: { crystals: 30 },
    icon: '✨',
  },
  {
    id: 'gold_500000000',
    category: 'resources',
    title: 'Wealth Beyond Measure',
    description: t('Earn a total of 500,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 500000000,
    reward: { crystals: 40 },
    icon: '💰',
  },
  {
    id: 'gold_1000000000',
    category: 'resources',
    title: 'Limitless Fortune',
    description: t('Earn a total of 1,000,000,000 gold.'),
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1000000000,
    reward: { crystals: 60 },
    icon: '💎',
  },
  // Crystals
  {
    id: 'crystals_5',
    category: 'resources',
    title: 'Crystal Seeker',
    description: t('Earn a total of 5 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 5,
    reward: { gold: 1000 },
    icon: '🔷',
  },
  {
    id: 'crystals_10',
    category: 'resources',
    title: 'Crystal Collector',
    description: t('Earn a total of 10 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 10,
    reward: { gold: 2000 },
    icon: '🔷',
  },
  {
    id: 'crystals_25',
    category: 'resources',
    title: 'Crystal Hoarder',
    description: t('Earn a total of 25 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 25,
    reward: { gold: 5000 },
    icon: '🔷',
  },
  {
    id: 'crystals_50',
    category: 'resources',
    title: 'Crystal Merchant',
    description: t('Earn a total of 50 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 50,
    reward: { gold: 10000 },
    icon: '💎',
  },
  {
    id: 'crystals_100',
    category: 'resources',
    title: 'Crystal Master',
    description: t('Earn a total of 100 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 100,
    reward: { gold: 25000 },
    icon: '💎',
  },
  {
    id: 'crystals_250',
    category: 'resources',
    title: 'Crystal Emperor',
    description: t('Earn a total of 250 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 250,
    reward: { gold: 50000 },
    icon: '💎',
  },
  {
    id: 'crystals_500',
    category: 'resources',
    title: 'Crystal God',
    description: t('Earn a total of 500 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 500,
    reward: { gold: 100000 },
    icon: '✨',
  },
  {
    id: 'crystals_1000',
    category: 'resources',
    title: 'Crystal Titan',
    description: t('Earn a total of 1,000 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 1000,
    reward: { gold: 250000 },
    icon: '✨',
  },
  {
    id: 'crystals_2000',
    category: 'resources',
    title: 'Crystal Deity',
    description: t('Earn a total of 2,000 crystals.'),
    type: 'resource',
    resource: 'crystals',
    target: 2000,
    reward: { gold: 500000 },
    icon: '👑',
  },
];
