export const ACHIEVEMENT_DEFINITIONS = [
  // Level Achievements
  {
    id: 'reach_level',
    title: 'achievements.data.reach_level.title',
    description: 'achievements.data.reach_level.desc',
    type: 'level',
    target: 50,
    baseTarget: 50,
    targetMultiplier: 5,
    maxLevel: 20,
    reward: { bonuses: { bonusExperiencePercent: 0.05 } },
    baseReward: { bonuses: { bonusExperiencePercent: 0.15 } },
    rewardMultiplier: 1.65,
    icon: 'text:LVL',
  },

  // Unique / Event-based Achievements
  {
    id: 'one_shot_kill',
    title: 'achievements.data.one_shot_kill.title',
    description: 'achievements.data.one_shot_kill.desc',
    type: 'event',
    eventType: 'kill',
    condition: (data) => data.isOneShot,
    target: 10,
    baseTarget: 10,
    targetMultiplier: 5,
    maxLevel: 5,
    reward: { bonuses: { allAttributes: 5 } },
    baseReward: { bonuses: { allAttributes: 5 } },
    rewardMultiplier: 2,
    icon: 'text:1HIT',
  },
  {
    id: 'summon_one_shot',
    title: 'achievements.data.summon_one_shot.title',
    description: 'achievements.data.summon_one_shot.desc',
    type: 'event',
    eventType: 'kill',
    condition: (data) => data.isOneShot && data.sourceType === 'summon',
    target: 10,
    baseTarget: 10,
    targetMultiplier: 5,
    maxLevel: 5,
    reward: { bonuses: { summonDamageBuffPercent: 0.1 } },
    baseReward: { bonuses: { summonDamageBuffPercent: 0.1 } },
    rewardMultiplier: 2,
    icon: 'text:SUM',
  },

  // Gold Achievements
  {
    id: 'earn_gold',
    title: 'achievements.data.earn_gold.title',
    description: 'achievements.data.earn_gold.desc',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1000,
    baseTarget: 1000,
    targetMultiplier: 10,
    maxLevel: 30,
    reward: { bonuses: { bonusGoldPercent: 0.10 } },
    baseReward: { bonuses: { bonusGoldPercent: 0.10 } },
    rewardMultiplier: 1.4,
    icon: 'text:GOLD',
  },

  // Combat Achievements
  {
    id: 'deal_damage',
    title: 'achievements.data.deal_damage.title',
    description: 'achievements.data.deal_damage.desc',
    type: 'damage',
    target: 1000,
    baseTarget: 1000,
    targetMultiplier: 5,
    maxLevel: 30,
    reward: { bonuses: { totalDamagePercent: 0.25 } },
    baseReward: { bonuses: { totalDamagePercent: 0.25 } },
    rewardMultiplier: 1.25,
    icon: 'text:DMG',
  },
  {
    id: 'survive_damage',
    title: 'achievements.data.survive_damage.title',
    description: 'achievements.data.survive_damage.desc',
    type: 'survival',
    target: 100,
    baseTarget: 100,
    targetMultiplier: 3.5,
    maxLevel: 20,
    reward: { bonuses: { armorPercent: 0.3, allResistancePercent: 0.3 } },
    baseReward: { bonuses: { armorPercent: 0.3, allResistancePercent: 0.3 } },
    rewardMultiplier: 1.3,
    icon: 'text:TANK',
  },
];
