import { t } from '../i18n.js';
/**
 * List of boss definitions for the Arena.
 * Each boss has a level, unique id, display name, image path, stats, and rewards.
 */

function applyDefaultBossStats(boss) {
  const defaults = {
    life: 4000,
    damage: 40,
    attackRating: 135,
    attackSpeed: 1,
    xp: 200,
    gold: 150,
    armor: 220,
    evasion: 150,
    fireDamage: 0,
    coldDamage: 0,
    airDamage: 0,
    earthDamage: 0,
    lightningDamage: 0,
    waterDamage: 0,
    fireResistance: 200,
    coldResistance: 200,
    airResistance: 200,
    earthResistance: 200,
    lightningResistance: 200,
    waterResistance: 200,
    multiplier: {
      life: 2,
      damage: 0.8,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 0.8,
      coldDamage: 0.8,
      airDamage: 0.8,
      earthDamage: 0.8,
      lightningDamage: 0.8,
      waterDamage: 0.8,

      fireResistance: 1,
      coldResistance: 1,
      airResistance: 1,
      earthResistance: 1,
      lightningResistance: 1,
      waterResistance: 1,
    },
  };
  const merged = { ...defaults, ...boss };
  if (boss.multiplier) {
    merged.multiplier = { ...defaults.multiplier, ...boss.multiplier };
  }
  return merged;
}

const RAW_BOSSES = [
  {
    id: 'goblin-king',
    name: t('Goblin King'),
    type: 'boss',
    image: '/enemies/goblin-king.jpg',
    attackSpeed: 1.2,
    damage: 30,
    coldDamage: 20,
    coldResistance: 400,
    fireResistance: 100,
    airResistance: 100,
    earthResistance: 100,
    lightningResistance: 100,
    waterResistance: 100,
    multiplier: {
      life: 1.2,
      damage: 1.1,
      gold: 1.2,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'ogre-chieftain',
    name: t('Ogre Chieftain'),
    type: 'boss',
    image: '/enemies/ogre-chieftain.jpg',
    attackSpeed: 1.5,
    damage: 17,
    fireDamage: 8,
    airDamage: 8,
    fireResistance: 310,
    airResistance: 120,
    earthResistance: 133,
    multiplier: {
      life: 1.75,
      damage: 1.2,
      fireDamage: 1.2,
      airDamage: 1.2,
      gold: 1.3,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'stone-golem',
    name: t('Stone Golem'),
    type: 'boss',
    image: '/enemies/obsidian-golem.jpg',
    damage: 25,
    attackSpeed: 1,
    life: 5000,
    coldDamage: 5,
    waterDamage: 5,
    earthResistance: 320,
    multiplier: {
      life: 2,
      damage: 1.2,
      xp: 1.4,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'fire-drake',
    name: t('Fire Drake'),
    type: 'boss',
    image: '/enemies/ember-drake.jpg',
    attackSpeed: 0.8,
    damage: 31,
    fireDamage: 27,
    fireResistance: 400,
    airResistance: 240,
    earthResistance: 200,
    lightningResistance: 300,
    waterResistance: 260,
    multiplier: {
      life: 1.6,
      damage: 1.2,
      xp: 1.2,
      gold: 1.2,
      fireDamage: 1.2,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
    // reward: { souls: 1, materials: [{ id: 'crystalized_rock', qty: 0 }] },
  },
  {
    id: 'ancient-serpent',
    name: t('Ancient Serpent'),
    type: 'boss',
    image: '/enemies/ancient-serpent.jpg',
    attackSpeed: 1.3,
    damage: 28,
    coldDamage: 15,
    coldResistance: 320,
    airResistance: 240,
    earthResistance: 245,
    lightningResistance: 200,
    waterResistance: 280,
    multiplier: {
      life: 1.7,
      damage: 1.2,
      xp: 1.3,
      gold: 1.4,
      coldDamage: 1.3,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
];

export const BOSSES = RAW_BOSSES.map(applyDefaultBossStats);