import { t } from '../i18n.js';
/**
 * List of boss definitions for the Arena.
 * Each boss has a level, unique id, display name, image path, stats, and rewards.
 */

function applyDefaultBossStats(boss) {
  const defaults = {
    life: 4000,
    damage: 40,
    attackRating: 135,
    attackSpeed: 1,
    xp: 200,
    gold: 150,
    armor: 220,
    evasion: 150,
    fireDamage: 0,
    coldDamage: 0,
    airDamage: 0,
    earthDamage: 0,
    lightningDamage: 0,
    waterDamage: 0,
    fireResistance: 200,
    coldResistance: 200,
    airResistance: 200,
    earthResistance: 200,
    lightningResistance: 200,
    waterResistance: 200,
    multiplier: {
      life: 2,
      damage: 0.8,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 0.8,
      coldDamage: 0.8,
      airDamage: 0.8,
      earthDamage: 0.8,
      lightningDamage: 0.8,
      waterDamage: 0.8,

      fireResistance: 1,
      coldResistance: 1,
      airResistance: 1,
      earthResistance: 1,
      lightningResistance: 1,
      waterResistance: 1,
    },
  };
  const merged = { ...defaults, ...boss };
  if (boss.multiplier) {
    merged.multiplier = { ...defaults.multiplier, ...boss.multiplier };
  }
  return merged;
}

const RAW_BOSSES = [
  {
    id: 'goblin-king',
    nameKey: 'enemy.goblinKing',
    type: 'boss',
    image: '/enemies/goblin-king.jpg',
    attackSpeed: 1.2,
    damage: 22,
    coldDamage: 20,
    coldResistance: 400,
    fireResistance: 100,
    airResistance: 100,
    earthResistance: 100,
    lightningResistance: 100,
    waterResistance: 100,
    multiplier: {
      life: 1.2,
      damage: 1.1,
      gold: 1.2,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'ogre-chieftain',
    nameKey: 'enemy.ogreChieftain',
    type: 'boss',
    image: '/enemies/ogre-chieftain.jpg',
    attackSpeed: 1.5,
    damage: 17,
    fireDamage: 8,
    airDamage: 8,
    fireResistance: 310,
    airResistance: 120,
    earthResistance: 133,
    multiplier: {
      life: 1.75,
      damage: 1.2,
      fireDamage: 1.2,
      airDamage: 1.2,
      gold: 1.3,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'stone-golem',
    nameKey: 'enemy.stoneGolem',
    type: 'boss',
    image: '/enemies/obsidian-golem.jpg',
    damage: 25,
    attackSpeed: 1,
    life: 5000,
    coldDamage: 5,
    waterDamage: 5,
    earthResistance: 320,
    multiplier: {
      life: 2,
      damage: 1.2,
      xp: 1.4,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'fire-drake',
    nameKey: 'enemy.fireDrake',
    type: 'boss',
    image: '/enemies/ember-drake.jpg',
    attackSpeed: 0.8,
    damage: 31,
    fireDamage: 27,
    fireResistance: 400,
    airResistance: 240,
    earthResistance: 200,
    lightningResistance: 300,
    waterResistance: 260,
    multiplier: {
      life: 1.6,
      damage: 1.2,
      xp: 1.2,
      gold: 1.2,
      fireDamage: 1.2,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
    // reward: { souls: 1, materials: [{ id: 'crystalized_rock', qty: 0 }] },
  },
  {
    id: 'ancient-serpent',
    nameKey: 'enemy.ancientSerpent',
    type: 'boss',
    image: '/enemies/ancient-serpent.jpg',
    attackSpeed: 1.3,
    damage: 26,
    coldDamage: 12,
    coldResistance: 320,
    airResistance: 240,
    earthResistance: 245,
    lightningResistance: 200,
    waterResistance: 280,
    multiplier: {
      life: 1.7,
      damage: 1.2,
      xp: 1.3,
      gold: 1.4,
      coldDamage: 1.3,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'void-harbinger',
    nameKey: 'enemy.voidHarbinger',
    type: 'boss',
    image: '/enemies/void-harbinger.jpg',
    attackSpeed: 1.1,
    damage: 24,
    fireDamage: 9,
    lightningDamage: 10,
    fireResistance: 380,
    lightningResistance: 420,
    coldResistance: 240,
    earthResistance: 260,
    multiplier: {
      life: 1.35,
      damage: 1.18,
      xp: 1.25,
      gold: 1.2,
      fireDamage: 1.15,
      lightningDamage: 1.2,
      lightningResistance: 1.1,
    },
    materialDropWeights: {},
    reward: { souls: 2 },
  },
  {
    id: 'ember-sovereign',
    nameKey: 'enemy.emberSovereign',
    type: 'boss',
    image: '/enemies/ember-sovereign.jpg',
    attackSpeed: 1.15,
    damage: 26,
    fireDamage: 15,
    fireResistance: 420,
    earthResistance: 320,
    airResistance: 220,
    multiplier: {
      life: 1.3,
      damage: 1.2,
      xp: 1.28,
      gold: 1.25,
      fireDamage: 1.25,
      fireResistance: 1.15,
    },
    materialDropWeights: {},
    reward: { souls: 2 },
  },
  {
    id: 'tempest-titan',
    nameKey: 'enemy.tempestTitan',
    type: 'boss',
    image: '/enemies/tempest-titan.jpg',
    attackSpeed: 1.05,
    damage: 28,
    airDamage: 12,
    lightningDamage: 9,
    airResistance: 400,
    lightningResistance: 360,
    fireResistance: 260,
    multiplier: {
      life: 1.38,
      damage: 1.18,
      xp: 1.3,
      gold: 1.28,
      airDamage: 1.25,
      lightningDamage: 1.2,
      evasion: 1.1,
    },
    materialDropWeights: {},
    reward: { souls: 3 },
  },
  {
    id: 'sandstorm-emperor',
    nameKey: 'enemy.sandstormEmperor',
    type: 'boss',
    image: '/enemies/sandstorm-emperor.jpg',
    attackSpeed: 1.15,
    damage: 26,
    earthDamage: 12,
    airDamage: 9,
    earthResistance: 420,
    airResistance: 320,
    fireResistance: 280,
    multiplier: {
      life: 1.4,
      damage: 1.22,
      armor: 1.15,
      xp: 1.32,
      gold: 1.28,
      earthDamage: 1.2,
      earthResistance: 1.15,
    },
    materialDropWeights: {},
    reward: { souls: 3 },
  },
  {
    id: 'radiant-phoenix',
    nameKey: 'enemy.radiantPhoenix',
    type: 'boss',
    image: '/enemies/radiant-phoenix.jpg',
    attackSpeed: 1.3,
    damage: 20,
    fireDamage: 14,
    airDamage: 9,
    fireResistance: 420,
    airResistance: 320,
    lightningResistance: 280,
    multiplier: {
      life: 1.32,
      damage: 1.26,
      xp: 1.35,
      gold: 1.32,
      fireDamage: 1.3,
      airDamage: 1.2,
      attackSpeed: 1.08,
    },
    materialDropWeights: {},
    reward: { souls: 3 },
  },
  {
    id: 'abyssal-leviathan',
    nameKey: 'enemy.abyssalLeviathan',
    type: 'boss',
    image: '/enemies/abyssal-leviathan.jpg',
    attackSpeed: 0.95,
    damage: 30,
    waterDamage: 14,
    coldDamage: 10,
    waterResistance: 440,
    coldResistance: 380,
    lightningResistance: 260,
    multiplier: {
      life: 1.42,
      damage: 1.24,
      xp: 1.34,
      gold: 1.32,
      waterDamage: 1.26,
      coldDamage: 1.18,
      waterResistance: 1.18,
    },
    materialDropWeights: {},
    reward: { souls: 3 },
  },
  {
    id: 'arcane-overseer',
    nameKey: 'enemy.arcaneOverseer',
    type: 'boss',
    image: '/enemies/arcane-overseer.jpg',
    attackSpeed: 1.05,
    damage: 28,
    lightningDamage: 10,
    airDamage: 9,
    fireDamage: 7,
    fireResistance: 320,
    lightningResistance: 340,
    coldResistance: 320,
    multiplier: {
      life: 1.36,
      damage: 1.22,
      xp: 1.35,
      gold: 1.32,
      attackRating: 1.14,
      airDamage: 1.2,
      lightningDamage: 1.22,
    },
    materialDropWeights: {},
    reward: { souls: 3 },
  },
  {
    id: 'glacial-tyrant',
    nameKey: 'enemy.glacialTyrant',
    type: 'boss',
    image: '/enemies/glacial-tyrant.jpg',
    attackSpeed: 0.95,
    damage: 30,
    coldDamage: 15,
    waterDamage: 10,
    coldResistance: 460,
    waterResistance: 360,
    fireResistance: 220,
    multiplier: {
      life: 1.45,
      damage: 1.24,
      armor: 1.18,
      xp: 1.36,
      gold: 1.34,
      coldDamage: 1.28,
      coldResistance: 1.2,
    },
    materialDropWeights: {},
    reward: { souls: 3 },
  },
];

export const BOSSES = RAW_BOSSES.map(applyDefaultBossStats);
