/**
 * List of boss definitions for the Arena.
 * Each boss has a level, unique id, display name, image path, stats, and rewards.
 */

function applyDefaultBossStats(boss) {
  const defaults = {
    life: 3000,
    damage: 40,
    attackRating: 320,
    attackSpeed: 1,
    xp: 600,
    gold: 1200,
    armor: 360,
    evasion: 360,
    fireDamage: 0,
    coldDamage: 0,
    airDamage: 0,
    earthDamage: 0,
    lightningDamage: 0,
    waterDamage: 0,
    fireResistance: 0,
    coldResistance: 0,
    airResistance: 0,
    earthResistance: 0,
    lightningResistance: 0,
    waterResistance: 0,
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
      lightningDamage: 1.0,
      waterDamage: 1.0,
    },
  };
  const merged = { ...defaults, ...boss };
  if (boss.multiplier) {
    merged.multiplier = { ...defaults.multiplier, ...boss.multiplier };
  }
  return merged;
}

const RAW_BOSSES = [
  {
    id: 'goblin-king',
    name: 'Goblin King',
    type: 'boss',
    image: '/enemies/goblin-king.jpg',
    attackSpeed: 1.2,
    coldDamage: 10,
    coldResistance: 60,
    multiplier: {
      life: 1.2,
      damage: 1.4,
      gold: 1.5,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'ogre-chieftain',
    name: 'Ogre Chieftain',
    type: 'boss',
    image: '/enemies/ogre-chieftain.jpg',
    attackSpeed: 1.5,
    damage: 20,
    fireDamage: 10,
    airDamage: 10,
    fireResistance: 50,
    airResistance: 50,
    earthResistance: 20,
    multiplier: {
      life: 2,
      damage: 1.3,
      fireDamage: 1.3,
      airDamage: 1.3,
      gold: 1.5,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'stone-golem',
    name: 'Stone Golem',
    type: 'boss',
    image: '/enemies/obsidian-golem.jpg',
    damage: 25,
    attackSpeed: 1,
    life: 3800,
    coldDamage: 5,
    waterDamage: 5,
    fireResistance: 30,
    airResistance: 30,
    earthResistance: 40,
    coldResistance: 30,
    lightningResistance: 30,
    waterResistance: 30,
    multiplier: {
      life: 1.8,
      damage: 1.3,
      xp: 1.6,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
  {
    id: 'fire-drake',
    name: 'Fire Drake',
    type: 'boss',
    image: '/enemies/ember-drake.jpg',
    attackSpeed: 0.8,
    damage: 30,
    fireDamage: 15,
    fireResistance: 50,
    airResistance: 30,
    earthResistance: 20,
    lightningResistance: 40,
    waterResistance: 30,
    multiplier: {
      life: 1.6,
      damage: 1.5,
      xp: 1.2,
      gold: 1.2,
      fireDamage: 1.4,
    },
    materialDropWeights: {},
    reward: { souls: 1, materials: [{ id: 'crystalized_rock', qty: 1 }] },
  },
  {
    id: 'ancient-serpent',
    name: 'Ancient Serpent',
    type: 'boss',
    image: '/enemies/ancient-serpent.jpg',
    attackSpeed: 1.3,
    damage: 28,
    coldDamage: 15,
    coldResistance: 55,
    airResistance: 35,
    earthResistance: 25,
    lightningResistance: 25,
    waterResistance: 40,
    multiplier: {
      life: 1.7,
      damage: 1.2,
      xp: 1.3,
      gold: 1.4,
      coldDamage: 1.3,
    },
    materialDropWeights: {},
    reward: { souls: 1 },
  },
];

export const BOSSES = RAW_BOSSES.map(applyDefaultBossStats);