import { ENEMY_LIST } from './enemies.js';

export const REGIONS = [
  {
    tier: 1,
    id: 'forest',
    unlockLevel: 1,
    name: 'Enchanted Forest',
    description: 'A mystical forest teeming with elemental creatures.',
    allowedTags: ['forest'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('forest')).map((e) => e.name);
    },
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      crystalized_rock: 1.1,
    },
    itemBaseBonus: 0.8,
  },
  {
    tier: 2,
    id: 'crystal_cave',
    unlockLevel: 25,
    name: 'Crystal Cave',
    description: 'A shimmering cave filled with crystalized rocks.',
    allowedTags: ['cave', 'crystal'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('cave')).map((e) => e.name);
    },
    multiplier: {
      life: 1.7,
      damage: 1.4,
      xp: 2.5,
      gold: 1,
      itemDrop: 1.0,
      materialDrop: 1.8,
      attackRating: 2.0,
      armor: 2.0,
      evasion: 2.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      crystalized_rock: 5,
    },
    itemBaseBonus: 1.04,
  },
  {
    tier: 3,
    id: 'tundra',
    unlockLevel: 50,
    name: 'Frozen Tundra',
    description: 'A land of ice and snow, home to cold and air enemies.',
    allowedTags: ['tundra', 'ice'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('tundra')).map((e) => e.name);
    },
    multiplier: {
      life: 2.4,
      damage: 2.0,
      xp: 3,
      gold: 2,
      itemDrop: 1.5,
      materialDrop: 1.0,
      attackRating: 3.0,
      armor: 3.0,
      evasion: 3.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      potion_of_strength: 3,
      potion_of_agility: 3,
      potion_of_vitality: 3,
    },
    itemBaseBonus: 1.28,
  },
  {
    tier: 4,
    id: 'desert',
    unlockLevel: 150,
    name: 'Scorching Desert',
    description: 'A vast desert with relentless heat and dangerous creatures.',
    allowedTags: ['desert', 'sand'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('desert')).map((e) => e.name);
    },
    multiplier: {
      life: 3,
      damage: 3.5,
      xp: 4,
      gold: 2.5,
      itemDrop: 1.5,
      materialDrop: 1.0,
      attackRating: 4.0,
      armor: 4.0,
      evasion: 4.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      elixir: 5,
    },
    canDrop: ['elixir'],
    itemBaseBonus: 1.52,
  },
  {
    tier: 5,
    id: 'swamp',
    unlockLevel: 350,
    name: 'Murky Swamp',
    description: 'A dark and damp swamp filled with poisonous creatures.',
    allowedTags: ['swamp', 'poison'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('swamp')).map((e) => e.name);
    },
    multiplier: {
      life: 6,
      damage: 3,
      xp: 4.5,
      gold: 2,
      itemDrop: 3,
      materialDrop: 2.0,
      attackRating: 5.0,
      armor: 5.0,
      evasion: 5.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      potion_of_endurance: 3,
      potion_of_wisdom: 3,
    },
    itemBaseBonus: 1.76,
  },
  {
    tier: 6,
    id: 'skyrealm',
    unlockLevel: 660,
    name: 'Skyrealm Peaks',
    description: 'A floating realm high above the clouds, home to air and lightning creatures.',
    allowedTags: ['sky', 'air'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('sky')).map((e) => e.name);
    },
    multiplier: {
      life: 7,
      damage: 5,
      xp: 5,
      gold: 3.5,
      itemDrop: 4,
      materialDrop: 1.0,
      attackRating: 6.0,
      armor: 6.0,
      evasion: 6.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      potion_of_dexterity: 5,
      potion_of_strength: 3,
      potion_of_agility: 3,
      potion_of_vitality: 3,
      potion_of_endurance: 3,
      potion_of_wisdom: 3,
    },
    itemBaseBonus: 2.0,
  },
  {
    tier: 7,
    id: 'abyss',
    unlockLevel: 1000,
    name: 'Abyssal Depths',
    description: 'A dark and mysterious region filled with ancient horrors.',
    allowedTags: ['abyss', 'dark'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('abyss')).map((e) => e.name);
    },
    multiplier: {
      life: 12,
      damage: 6,
      xp: 9,
      gold: 4,
      itemDrop: 1.0,
      materialDrop: 5.0,
      attackRating: 7.0,
      armor: 7.0,
      evasion: 7.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      freaky_gold_coins: 15,
    },
    itemBaseBonus: 2.24,
  },
  {
    tier: 8,
    id: 'volcanic_rift',
    unlockLevel: 1400,
    name: 'Volcanic Rift',
    description: 'A searing landscape of molten rock and fire elementals.',
    allowedTags: ['volcano', 'fire'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('volcano') || e.tags.includes('fire'))).map(
        (e) => e.name
      );
    },
    multiplier: {
      life: 18,
      damage: 12,
      xp: 12,
      gold: 10,
      itemDrop: 7.0,
      materialDrop: 1,
      attackRating: 8.0,
      armor: 8.0,
      evasion: 8.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      potion_of_strength: 4,
      armor_upgrade_stone: 2.2,
      weapon_upgrade_core: 1.2,
    },
    itemBaseBonus: 2.48,
  },
  {
    tier: 9,
    id: 'sunken_ruins',
    unlockLevel: 1800,
    name: 'Sunken Ruins',
    description: 'Ancient ruins submerged beneath the waves, teeming with aquatic mysteries.',
    allowedTags: ['ruins', 'water'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('ruins') || e.tags.includes('water'))).map(
        (e) => e.name
      );
    },
    multiplier: {
      life: 22,
      damage: 16,
      xp: 16,
      gold: 15,
      itemDrop: 4,
      materialDrop: 4,
      attackRating: 9.0,
      armor: 9.0,
      evasion: 9.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      potion_of_vitality: 3.1,
      crystalized_rock: 2.2,
    },
    itemBaseBonus: 2.72,
  },
  {
    tier: 10,
    id: 'haunted_moor',
    unlockLevel: 2200,
    name: 'Haunted Moor',
    description: 'A fog-laden moor haunted by restless spirits and lost souls.',
    allowedTags: ['haunted', 'spirit'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('haunted') || e.tags.includes('spirit'))).map(
        (e) => e.name
      );
    },
    multiplier: {
      life: 35,
      damage: 25,
      xp: 25,
      gold: 15,
      itemDrop: 12,
      materialDrop: 1.0,
      attackRating: 10.0,
      armor: 10.0,
      evasion: 10.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      potion_of_wisdom: 3.2,
      elixir: 1.3,
    },
    canDrop: ['elixir'],
    itemBaseBonus: 2.96,
  },
  {
    tier: 11,
    id: 'golden_steppe',
    unlockLevel: 2600,
    name: 'Golden Steppe',
    description: 'Vast golden grasslands where fortune favors the bold.',
    allowedTags: ['steppe', 'gold'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('steppe') || e.tags.includes('gold'))).map(
        (e) => e.name
      );
    },
    multiplier: {
      life: 30,
      damage: 35,
      xp: 25,
      gold: 30,
      itemDrop: 6.0,
      materialDrop: 6.0,
      attackRating: 11.0,
      armor: 11.0,
      evasion: 11.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      medium_gold_coins: 3.2,
      large_gold_coins: 1.2,
    },
    itemBaseBonus: 3.22,
  },
  {
    tier: 12,
    id: 'obsidian_spire',
    unlockLevel: 3000,
    name: 'Obsidian Spire',
    description: 'A towering spire of black glass, pulsing with arcane energy.',
    allowedTags: ['obsidian', 'arcane'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('obsidian') || e.tags.includes('arcane'))).map(
        (e) => e.name
      );
    },
    multiplier: {
      life: 60,
      damage: 60,
      xp: 50,
      gold: 50,
      itemDrop: 10,
      materialDrop: 10,
      attackRating: 12.0,
      armor: 12.0,
      evasion: 12.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
    },
    materialDropWeights: {
      jewelry_upgrade_gem: 2.2,
      potion_of_dexterity: 2.1,
      weapon_upgrade_core: 1.3,
    },
    itemBaseBonus: 3.5,
  },
];

export function getRegionByTier(tier) {
  return REGIONS.find((region) => region.tier === tier);
}
