import { ENEMY_LIST } from './enemies.js';

export const REGIONS = [
  {
    tier: 1,
    id: 'forest',
    unlockLevel: 1,
    name: 'Enchanted Forest',
    description: 'A mystical forest teeming with elemental creatures.',
    allowedTags: ['forest'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('forest')).map((e) => e.name);
    },
    multiplier: {
      life: 1.0,
      damage: 1.0,
      xp: 1.0,
      gold: 1.0,
      itemDrop: 1.0,
      materialDrop: 1.0,
      attackRating: 1.0,
      armor: 1.0,
      evasion: 1.0,
      fireDamage: 1.0,
      coldDamage: 1.0,
      airDamage: 1.0,
      earthDamage: 1.0,
      lightningDamage: 1.0,
      waterDamage: 1.0,
    },
    materialDropWeights: {
      crystalized_rock: 1.1,
    },
    itemBaseBonus: 0.8,
  },
  {
    tier: 2,
    id: 'crystal_cave',
    unlockLevel: 25,
    name: 'Crystal Cave',
    description: 'A shimmering cave filled with rocks. Has a high chance of dropping crystalized rocks.',
    allowedTags: ['cave', 'crystal'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('cave')).map((e) => e.name);
    },
    multiplier: {
      life: 1.7,
      damage: 1.4,
      xp: 1.5,
      gold: 1.1,
      itemDrop: 1.0,
      materialDrop: 1.5,
      attackRating: 1.5,
      armor: 1.5,
      evasion: 1.5,
      fireDamage: 1.5,
      coldDamage: 1.5,
      airDamage: 1.5,
      earthDamage: 1.5,
      lightningDamage: 1.5,
      waterDamage: 1.5,
    },
    materialDropWeights: {
      crystalized_rock: 5,
    },
    itemBaseBonus: 1.05,
  },
  {
    tier: 3,
    id: 'tundra',
    unlockLevel: 50,
    name: 'Frozen Tundra',
    description: 'A land of ice and snow, home to cold and air enemies. Has increased chance of dropping potions.',
    allowedTags: ['tundra', 'ice'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('tundra')).map((e) => e.name);
    },
    multiplier: {
      life: 2.5,
      damage: 2,
      xp: 2,
      gold: 1.3,
      itemDrop: 1.2,
      materialDrop: 1.4,
      attackRating: 2,
      armor: 2,
      evasion: 2,
      fireDamage: 2,
      coldDamage: 2,
      airDamage: 2,
      earthDamage: 2,
      lightningDamage: 2,
      waterDamage: 2,
    },
    materialDropWeights: {
      potion_of_strength: 3,
      potion_of_agility: 3,
      potion_of_vitality: 3,
      potion_of_endurance: 3,
      potion_of_wisdom: 3,
      potion_of_dexterity: 3,
      potion_of_intelligence: 3,
      potion_of_perseverance: 3,
    },
    itemBaseBonus: 1.3,
  },
  {
    tier: 4,
    id: 'desert',
    unlockLevel: 150,
    name: 'Scorching Desert',
    description: 'A vast desert with relentless heat and dangerous creatures. Has a chance to drop elixirs.',
    allowedTags: ['desert', 'sand'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('desert')).map((e) => e.name);
    },
    multiplier: {
      life: 3,
      damage: 2.7,
      xp: 2.2,
      gold: 1.7,
      itemDrop: 1.4,
      materialDrop: 1.7,
      attackRating: 2.7,
      armor: 2.7,
      evasion: 2.7,
      fireDamage: 2.7,
      coldDamage: 2.7,
      airDamage: 2.7,
      earthDamage: 2.7,
      lightningDamage: 2.7,
      waterDamage: 2.7,
    },
    materialDropWeights: {
      elixir: 5,
    },
    canDrop: ['elixir'],
    itemBaseBonus: 1.55,
  },
  {
    tier: 5,
    id: 'swamp',
    unlockLevel: 350,
    name: 'Murky Swamp',
    description: 'A dark and damp swamp filled with poisonous creatures. Has increased chance of dropping gold coins.',
    allowedTags: ['swamp', 'poison'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('swamp')).map((e) => e.name);
    },
    multiplier: {
      life: 4,
      damage: 3.5,
      xp: 2.5,
      gold: 2.2,
      itemDrop: 1.7,
      materialDrop: 2,
      attackRating: 3.5,
      armor: 3.5,
      evasion: 3.5,
      fireDamage: 3.5,
      coldDamage: 3.5,
      airDamage: 3.5,
      earthDamage: 3.5,
      lightningDamage: 3.5,
      waterDamage: 3.5,
    },
    materialDropWeights: {
      gold_coins: 4,
      large_gold_coins: 5,
      enormous_gold_coins: 6,
      FREAKY_GOLD_COINS: 4,
    },
    itemBaseBonus: 1.8,
  },
  {
    tier: 6,
    id: 'skyrealm',
    unlockLevel: 660,
    name: 'Skyrealm Peaks',
    description: 'A floating realm high above the clouds, home to air and lightning creatures. Has a higher chance to drop potions.',
    allowedTags: ['sky', 'air'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('sky')).map((e) => e.name);
    },
    multiplier: {
      life: 6,
      damage: 5,
      xp: 3.2,
      gold: 2.7,
      itemDrop: 4,
      materialDrop: 1,
      attackRating: 5,
      armor: 5,
      evasion: 5,
      fireDamage: 5,
      coldDamage: 5,
      airDamage: 5,
      earthDamage: 5,
      lightningDamage: 5,
      waterDamage: 5,
    },
    materialDropWeights: {
      potion_of_dexterity: 3,
      potion_of_strength: 3,
      potion_of_agility: 3,
      potion_of_vitality: 3,
      potion_of_endurance: 3,
      potion_of_wisdom: 3,
      potion_of_intelligence: 3,
      potion_of_perseverance: 3,
    },
    itemBaseBonus: 2.1,
  },
  {
    tier: 7,
    id: 'abyss',
    unlockLevel: 1000,
    name: 'Abyssal Depths',
    description: 'A dark and mysterious region filled with ancient horrors. Has a chance to drop high value gold coins.',
    allowedTags: ['abyss', 'dark'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && e.tags.includes('abyss')).map((e) => e.name);
    },
    multiplier: {
      life: 8,
      damage: 7,
      xp: 4,
      gold: 3.5,
      itemDrop: 2.8,
      materialDrop: 2.5,
      attackRating: 7,
      armor: 7,
      evasion: 7,
      fireDamage: 7,
      coldDamage: 7,
      airDamage: 7,
      earthDamage: 7,
      lightningDamage: 7,
      waterDamage: 7,
    },
    materialDropWeights: {
      enormous_gold_coins: 6,
      freaky_gold_coins: 20,
    },
    itemBaseBonus: 2.4,
  },
  {
    tier: 8,
    id: 'volcanic_rift',
    unlockLevel: 1400,
    name: 'Volcanic Rift',
    description: 'A searing landscape of molten rock and fire elementals. Has a higher chance to drop item upgrade materials.',
    allowedTags: ['volcano', 'fire'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('volcano') || e.tags.includes('fire'))).map(
        (e) => e.name,
      );
    },
    multiplier: {
      life: 9,
      damage: 10,
      xp: 5.5,
      gold: 4,
      itemDrop: 1,
      materialDrop: 6,
      attackRating: 9,
      armor: 9,
      evasion: 9,
      fireDamage: 9,
      coldDamage: 9,
      airDamage: 9,
      earthDamage: 9,
      lightningDamage: 9,
      waterDamage: 9,
    },
    materialDropWeights: {
      jewelry_upgrade_gem: 5,
      armor_upgrade_stone: 3,
      weapon_upgrade_core: 6,
    },
    itemBaseBonus: 2.7,
  },
  {
    tier: 9,
    id: 'sunken_ruins',
    unlockLevel: 1800,
    name: 'Sunken Ruins',
    description: 'Ancient ruins submerged beneath the waves, teeming with aquatic mysteries. Has a chance to drop elixirs and higher chance to drop crystalized rocks.',
    allowedTags: ['ruins', 'water'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('ruins') || e.tags.includes('water'))).map(
        (e) => e.name,
      );
    },
    multiplier: {
      life: 15,
      damage: 14,
      xp: 7,
      gold: 4,
      itemDrop: 4,
      materialDrop: 4,
      attackRating: 12,
      armor: 12,
      evasion: 12,
      fireDamage: 12,
      coldDamage: 12,
      airDamage: 12,
      earthDamage: 12,
      lightningDamage: 12,
      waterDamage: 12,
    },
    canDrop: ['elixir'],
    materialDropWeights: {
      elixir: 3.5,
      crystalized_rock: 6,
    },
    itemBaseBonus: 2.95,
  },
  {
    tier: 10,
    id: 'haunted_moor',
    unlockLevel: 2200,
    name: 'Haunted Moor',
    description: 'A fog-laden moor haunted by restless spirits and lost souls. Has a higher chance to drop experience potions.',
    allowedTags: ['haunted', 'spirit'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('haunted') || e.tags.includes('spirit'))).map(
        (e) => e.name,
      );
    },
    multiplier: {
      life: 25,
      damage: 25,
      xp: 7,
      gold: 7,
      itemDrop: 8,
      materialDrop: 2,
      attackRating: 25,
      armor: 25,
      evasion: 25,
      fireDamage: 25,
      coldDamage: 25,
      airDamage: 25,
      earthDamage: 25,
      lightningDamage: 25,
      waterDamage: 25,
    },
    materialDropWeights: {
      greater_experience_potion: 6,
      huge_experience_potion: 10,
    },
    itemBaseBonus: 3.15,
  },
  {
    tier: 11,
    id: 'golden_steppe',
    unlockLevel: 2600,
    name: 'Golden Steppe',
    description: 'Vast golden grasslands where fortune favors the bold.',
    allowedTags: ['steppe', 'gold'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('steppe') || e.tags.includes('gold'))).map(
        (e) => e.name,
      );
    },
    multiplier: {
      life: 30,
      damage: 30,
      xp: 7,
      gold: 15,
      itemDrop: 6.0,
      materialDrop: 6.0,
      attackRating: 28,
      armor: 28,
      evasion: 28,
      fireDamage: 30,
      coldDamage: 30,
      airDamage: 30,
      earthDamage: 30,
      lightningDamage: 30,
      waterDamage: 30,
    },
    materialDropWeights: {
    },
    itemBaseBonus: 3.22,
  },
  {
    tier: 12,
    id: 'obsidian_spire',
    unlockLevel: 3000,
    name: 'Obsidian Spire',
    description: 'A towering spire of black glass, pulsing with arcane energy. Has a higher chance of dropping crafting materials.',
    allowedTags: ['obsidian', 'arcane'],
    get enemyNames() {
      return ENEMY_LIST.filter((e) => e.tags && (e.tags.includes('obsidian') || e.tags.includes('arcane'))).map(
        (e) => e.name,
      );
    },
    multiplier: {
      life: 50,
      damage: 50,
      xp: 14,
      gold: 9,
      itemDrop: 10,
      materialDrop: 7,
      attackRating: 40,
      armor: 40,
      evasion: 40,
      fireDamage: 50,
      coldDamage: 50,
      airDamage: 50,
      earthDamage: 50,
      lightningDamage: 50,
      waterDamage: 50,
    },
    materialDropWeights: {
      enchantment_scroll: 5,
      alternation_orb: 5,
    },
    itemBaseBonus: 3.6,
  },
];

export function getRegionByTier(tier) {
  return REGIONS.find((region) => region.tier === tier);
}
