import { ITEM_IDS } from './items.js';

export const UNIQUE_ITEMS = {
  stormlash: {
    id: 'stormlash',
    nameKey: 'items.unique.stormlash',
    type: ITEM_IDS.SWORD,
    dropWeight: 8,
    stats: {
      damagePercent: { minMultiplier: -9999, maxMultiplier: -9999 },
      lightningDamage: { minMultiplier: 1.0, maxMultiplier: 2 },
      lightningDamagePercent: { minMultiplier: 1.0, maxMultiplier: 1.4 },
      attackSpeedPercent: { minMultiplier: 1.0, maxMultiplier: 1.2 },
      critChance: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      attackRating: { minMultiplier: 0.9, maxMultiplier: 1.4 },
    },
  },
  nightveil_hood: {
    id: 'nightveil_hood',
    nameKey: 'items.unique.nightveilHood',
    type: ITEM_IDS.HELMET,
    dropWeight: 15,
    stats: {
      dexterity: { minMultiplier: 1.0, maxMultiplier: 1.4 },
      evasionPercent: { minMultiplier: 1.0, maxMultiplier: 1.2 },
      critChance: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      manaRegenPercent: { minMultiplier: 0.9, maxMultiplier: 1.2 },
    },
  },
  phoenixheart_mantle: {
    id: 'phoenixheart_mantle',
    nameKey: 'items.unique.phoenixheartMantle',
    type: ITEM_IDS.ARMOR,
    dropWeight: 12,
    stats: {
      life: { minMultiplier: 1.0, maxMultiplier: 1.6 },
      lifeRegenPercent: { minMultiplier: 0.9, maxMultiplier: 1.4 },
      fireDamagePercent: { minMultiplier: 1.0, maxMultiplier: 1.3 },
      fireResistancePercent: { minMultiplier: 0.9, maxMultiplier: 1.3 },
    },
  },
  maelstrom_core: {
    id: 'maelstrom_core',
    nameKey: 'items.unique.maelstromCore',
    type: ITEM_IDS.AMULET,
    dropWeight: 6,
    stats: {
      lightningDamagePercent: { minMultiplier: 1.0, maxMultiplier: 1.2 },
      elementalPenetration: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      extraDamageFromAttackRatingPercent: { minMultiplier: 0.9, maxMultiplier: 1.1 },
      manaRegenOfTotalPercent: { minMultiplier: 1.0, maxMultiplier: 1.4 },
    },
  },
  tempestbind_grips: {
    id: 'tempestbind_grips',
    nameKey: 'items.unique.tempestbindGrips',
    type: ITEM_IDS.GLOVES,
    dropWeight: 10,
    stats: {
      attackSpeedPercent: { minMultiplier: 1.0, maxMultiplier: 1.3 },
      elementalDamage: { minMultiplier: 1.0, maxMultiplier: 1.3 },
      critDamage: { minMultiplier: 1.0, maxMultiplier: 1.2 },
      chanceToHitPercent: { minMultiplier: 0.9, maxMultiplier: 1.1 },
    },
  },
  riftstrider_boots: {
    id: 'riftstrider_boots',
    nameKey: 'items.unique.riftstriderBoots',
    type: ITEM_IDS.BOOTS,
    dropWeight: 14,
    stats: {
      evasion: { minMultiplier: 1.0, maxMultiplier: 1.6 },
      allResistancePercent: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      endurance: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      omniSteal: { minMultiplier: 0.9, maxMultiplier: 1.1 },
    },
  },
  ribbonweave_vestments: {
    id: 'ribbonweave_vestments',
    nameKey: 'items.unique.ribbonweaveVestments',
    type: ITEM_IDS.ARMOR,
    dropWeight: 4,
    stats: {
      allAttributes: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      allResistance: { minMultiplier: 0.5, maxMultiplier: 0.7 },
      armor: { minMultiplier: 0.3, maxMultiplier: 0.5 },
      evasion: { minMultiplier: 0.3, maxMultiplier: 0.5 },
      lifeRegen: { minMultiplier: 0.5, maxMultiplier: 0.5 },
      manaRegen: { minMultiplier: 0.4, maxMultiplier: 0.6 },
      damage: { minMultiplier: 0.3, maxMultiplier: 0.6 },
      elementalDamage: { minMultiplier: 0.3, maxMultiplier: 0.6 },
      attackRating: { minMultiplier: 0.6, maxMultiplier: 0.8 },
    },
  },
};
