import { ITEM_IDS } from './items.js';

export const UNIQUE_ITEMS = {
  stormlash: {
    id: 'stormlash',
    nameKey: 'items.unique.stormlash',
    type: ITEM_IDS.SWORD,
    dropWeight: 8,
    stats: {
      damagePercent: { minMultiplier: -50, maxMultiplier: -10 },
      lightningDamage: { minMultiplier: 1.5, maxMultiplier: 5 },
      lightningDamagePercent: { minMultiplier: 1.0, maxMultiplier: 3 },
      attackSpeedPercent: { minMultiplier: 1.0, maxMultiplier: 1.5 },
      critChance: { minMultiplier: 0.8, maxMultiplier: 1.5 },
      attackRating: { minMultiplier: 0.7, maxMultiplier: 3 },
    },
  },
  nightveil_hood: {
    id: 'nightveil_hood',
    nameKey: 'items.unique.nightveilHood',
    type: ITEM_IDS.HELMET,
    dropWeight: 15,
    stats: {
      dexterity: { minMultiplier: 1.5, maxMultiplier: 2 },
      evasionPercent: { minMultiplier: 1.5, maxMultiplier: 2 },
      critChance: { minMultiplier: 0.9, maxMultiplier: 1.4 },
      manaRegenPercent: { minMultiplier: 0.9, maxMultiplier: 2.2 },
      cooldownReductionPercent: { minMultiplier: 0.5, maxMultiplier: 2 },
    },
  },
  phoenixheart_mantle: {
    id: 'phoenixheart_mantle',
    nameKey: 'items.unique.phoenixheartMantle',
    type: ITEM_IDS.ARMOR,
    dropWeight: 12,
    stats: {
      life: { minMultiplier: 1.0, maxMultiplier: 2.5 },
      lifeRegenPercent: { minMultiplier: 0.9, maxMultiplier: 2 },
      fireDamagePercent: { minMultiplier: 1.0, maxMultiplier: 1.5 },
      fireResistancePercent: { minMultiplier: 0.9, maxMultiplier: 2.5 },
    },
  },
  maelstrom_core: {
    id: 'maelstrom_core',
    nameKey: 'items.unique.maelstromCore',
    type: ITEM_IDS.AMULET,
    dropWeight: 6,
    stats: {
      lightningDamagePercent: { minMultiplier: 1.0, maxMultiplier: 1.2 },
      elementalPenetration: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      extraDamageFromAttackRatingPercent: { minMultiplier: 0.9, maxMultiplier: 1.1 },
      manaRegenOfTotalPercent: { minMultiplier: 1.0, maxMultiplier: 1.4 },
    },
  },
  tempestbind_grips: {
    id: 'tempestbind_grips',
    nameKey: 'items.unique.tempestbindGrips',
    type: ITEM_IDS.GLOVES,
    dropWeight: 10,
    stats: {
      attackSpeedPercent: { minMultiplier: 1.0, maxMultiplier: 1.3 },
      elementalDamage: { minMultiplier: 1.0, maxMultiplier: 1.3 },
      critDamagePercent: { minMultiplier: 1.0, maxMultiplier: 1.2 },
      chanceToHitPercent: { minMultiplier: 0.9, maxMultiplier: 1.1 },
    },
  },
  riftstrider_boots: {
    id: 'riftstrider_boots',
    nameKey: 'items.unique.riftstriderBoots',
    type: ITEM_IDS.BOOTS,
    dropWeight: 14,
    stats: {
      evasion: { minMultiplier: 1.0, maxMultiplier: 1.6 },
      allResistancePercent: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      endurance: { minMultiplier: 0.9, maxMultiplier: 1.2 },
      omniSteal: { minMultiplier: 0.9, maxMultiplier: 1.1 },
    },
  },
  ribbonweave_vestments: {
    id: 'ribbonweave_vestments',
    nameKey: 'items.unique.ribbonweaveVestments',
    type: ITEM_IDS.ARMOR,
    dropWeight: 8,
    stats: {
      allAttributes: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      allResistance: { minMultiplier: 0.5, maxMultiplier: 0.7 },
      armor: { minMultiplier: 0.3, maxMultiplier: 0.5 },
      evasion: { minMultiplier: 0.3, maxMultiplier: 0.5 },
      lifeRegen: { minMultiplier: 0.5, maxMultiplier: 0.5 },
      manaRegen: { minMultiplier: 0.4, maxMultiplier: 0.6 },
      damage: { minMultiplier: 0.3, maxMultiplier: 0.6 },
      elementalDamage: { minMultiplier: 0.3, maxMultiplier: 0.6 },
      attackRating: { minMultiplier: 0.6, maxMultiplier: 0.8 },
    },
  },

  // NEW UNIQUE ITEMS
  the_monolith: {
    id: 'the_monolith',
    nameKey: 'items.unique.theMonolith',
    type: ITEM_IDS.SHIELD,
    dropWeight: 20,
    stats: { armor: { minMultiplier: 4.0, maxMultiplier: 8.0 } },
  },
  midas_touch: {
    id: 'midas_touch',
    nameKey: 'items.unique.midasTouch',
    type: ITEM_IDS.DAGGER,
    dropWeight: 2,
    stats: {
      bonusGoldPercent: { minMultiplier: 3.0, maxMultiplier: 5.0 },
      instaKillPercent: { minMultiplier: 0.2, maxMultiplier: 0.5 },
    },
  },
  absolute_zero: {
    id: 'absolute_zero',
    nameKey: 'items.unique.absoluteZero',
    type: ITEM_IDS.WAND,
    dropWeight: 6,
    stats: {
      coldDamage: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      coldDamagePercent: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      waterDamage: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      waterDamagePercent: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      freezeChance: { minMultiplier: 0.6, maxMultiplier: 1.2 },
      chanceToShatterEnemy: { minMultiplier: 0.6, maxMultiplier: 1.2 },
      extraDamageAgainstFrozenEnemies: { minMultiplier: 0.6, maxMultiplier: 1.2 },
      coldDamageTakenReductionPercent: { minMultiplier: 0.6, maxMultiplier: 1.2 },
    },
  },
  glass_cannon: {
    id: 'glass_cannon',
    nameKey: 'items.unique.glassCannon',
    type: ITEM_IDS.AMULET,
    dropWeight: 3,
    stats: {
      damagePercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      allResistancePercent: { minMultiplier: -0.8, maxMultiplier: -0.5 },
      lifePercent: { minMultiplier: -0.8, maxMultiplier: -0.5 },
      avoidChance: { minMultiplier: 1.0, maxMultiplier: 1.0 },
      critDamagePercent: { minMultiplier: 1.2, maxMultiplier: 2.0 },
    },
  },
  blood_gods_carapace: {
    id: 'blood_gods_carapace',
    nameKey: 'items.unique.bloodGodsCarapace',
    type: ITEM_IDS.ARMOR,
    dropWeight: 8,
    stats: {
      lifeRegenOfTotalPercent: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      lifeSteal: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      omniSteal: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      bleedChance: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      bleedDamagePercent: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      armorPercent: { minMultiplier: -1.0, maxMultiplier: -0.8 },
    },
  },
  the_untouchable: {
    id: 'the_untouchable',
    nameKey: 'items.unique.theUntouchable',
    type: ITEM_IDS.BOOTS,
    dropWeight: 4,
    stats: {
      teleportDodgeChance: { minMultiplier: 1.0, maxMultiplier: 1.0 },
      avoidChance: { minMultiplier: 1.0, maxMultiplier: 1.0 },
      evasionPercent: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      extraDamageFromEvasionPercent: { minMultiplier: 1.0, maxMultiplier: 1.5 },
    },
  },
  overlords_command: {
    id: 'overlords_command',
    nameKey: 'items.unique.overlordsCommand',
    type: ITEM_IDS.RING,
    dropWeight: 2,
    stats: {
      summonDamageBuffPercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      summonAttackSpeedBuffPercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      damagePercent: { minMultiplier: -1, maxMultiplier: -0.2 },
    },
  },
  infernos_heart: {
    id: 'infernos_heart',
    nameKey: 'items.unique.infernosHeart',
    type: ITEM_IDS.STAFF,
    dropWeight: 8,
    stats: {
      fireDamage: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      fireDamagePercent: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      burnChance: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      burnDamagePercent: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      extraDamageAgainstBurningEnemies: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      explosionChance: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      fireResistancePercent: { minMultiplier: 0.6, maxMultiplier: 0.9 },
      elementalPenetrationPercent: { minMultiplier: 0.6, maxMultiplier: 0.9 },
    },
  },
  titans_grip: {
    id: 'titans_grip',
    nameKey: 'items.unique.titansGrip',
    type: ITEM_IDS.GLOVES,
    dropWeight: 8,
    stats: {
      strengthPercent: { minMultiplier: 1, maxMultiplier: 2 },
      weaponEffectivenessPercent: { minMultiplier: 1.2, maxMultiplier: 2.0 },
      attackSpeedPercent: { minMultiplier: -0.6, maxMultiplier: -0.4 },
      damagePercent: { minMultiplier: 1, maxMultiplier: 2 },
    },
  },
  alchemists_greed: {
    id: 'alchemists_greed',
    nameKey: 'items.unique.alchemistsGreed',
    type: ITEM_IDS.AMULET,
    dropWeight: 8,
    stats: {
      itemQuantityPercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      itemRarityPercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      materialQuantityPercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      enemyRarityPercent: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      damagePercent: { minMultiplier: -0.5, maxMultiplier: -0.3 },
      allResistancePercent: { minMultiplier: -0.5, maxMultiplier: -0.3 },
    },
  },
  infinity_loop: {
    id: 'infinity_loop',
    nameKey: 'items.unique.infinityLoop',
    type: ITEM_IDS.RING,
    dropWeight: 1,
    stats: {
      cooldownReductionPercent: { minMultiplier: 0.5, maxMultiplier: 2.5 },
      buffDurationPercent: { minMultiplier: 0.5, maxMultiplier: 2.5 },
      attackSpeedPercent: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      manaCostReductionPercent: { minMultiplier: 0.8, maxMultiplier: 1.2 },
    },
  },
  sunbreakers_resolve: {
    id: 'sunbreakers_resolve',
    nameKey: 'items.unique.sunbreakersResolve',
    type: ITEM_IDS.MACE,
    dropWeight: 4,
    stats: {
      healDamagesEnemiesPercent: { minMultiplier: 1, maxMultiplier: 1.5 },
      lifeRegenOfTotalPercent: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      overhealPercent: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      buffEffectivenessPercent: { minMultiplier: 0.8, maxMultiplier: 1.2 },
    },
  },
  berserkers_adrenaline: {
    id: 'berserkers_adrenaline',
    nameKey: 'items.unique.berserkersAdrenaline',
    type: ITEM_IDS.AXE,
    dropWeight: 8,
    stats: {
      attackSpeedPercent: { minMultiplier: 1.5, maxMultiplier: 2.5 },
      doubleDamageChance: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      lifePerHit: { minMultiplier: 0.8, maxMultiplier: 1.2 },
      damagePercent: { minMultiplier: -0.4, maxMultiplier: -0.2 },
    },
  },
  voidwalkers_mantle: {
    id: 'voidwalkers_mantle',
    nameKey: 'items.unique.voidwalkersMantle',
    type: ITEM_IDS.ARMOR,
    dropWeight: 8,
    stats: {
      reduceEnemyHpPercent: { minMultiplier: 1.2, maxMultiplier: 1.8 },
      damageTakenReductionPercent: { minMultiplier: 1.0, maxMultiplier: 1.5 },
      arenaDamageReductionPercent: { minMultiplier: 1.0, maxMultiplier: 1.5 },
      lifePercent: { minMultiplier: -0.5, maxMultiplier: -0.3 },
    },
  },
};
