import { DEFAULT_MAX_SKILL_LEVEL, SKILL_LEVEL_TIERS } from '../../skillTree.js';
import { scaleDownFlat, scaleUpFlat } from '../../common.js';

// Elementalist skills extracted from skills.js
export const ELEMENTALIST_SKILLS = {
  // Tier 1 Skills
  fireball: {
    id: 'fireball',
    name: () => 'Fireball',
    type: () => 'instant',
    manaCost: (level) => 2 + level * 0.25,
    cooldown: () => 5200,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'fireball',
    description: () => 'Launches a fireball that deals fire damage.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamage: scaleUpFlat(level, 2, 6),
      fireDamagePercent: scaleDownFlat(level, 5),
    }),
  },
  frostArmor: {
    id: 'frostArmor',
    name: () => 'Frost Armor',
    type: () => 'buff',
    manaCost: (level) => 6 + level * 1.25,
    cooldown: () => 34000,
    duration: () => 10000,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'frost-armor',
    description: () => 'Encases the caster in frost, increasing armor.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      armor: scaleUpFlat(level, 4, 8),
      armorPercent: scaleDownFlat(level, 3),
      coldDamagePercent: scaleDownFlat(level, 2),
    }),
  },

  warmth: {
    id: 'warmth',
    name: () => 'Warmth',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'storm',
    description: () => 'Increases mana and mana regeneration',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      manaPercent: scaleDownFlat(level, 2),
      manaRegen: scaleUpFlat(level, 0.2),
      manaRegenPercent: scaleDownFlat(level, 0.8),
      wisdomPercent: scaleDownFlat(level, 0.5),
      wisdom: scaleUpFlat(level, 2),
    }),
  },

  // Tier 10 Skills
  lightningStrike: {
    id: 'lightningStrike',
    name: () => 'Lightning Strike',
    type: () => 'instant',
    manaCost: (level) => 4 + level * 0.375,
    cooldown: () => 3000,
    requiredLevel: () => SKILL_LEVEL_TIERS[1],
    icon: () => 'lightning',
    description: () => 'Strikes an enemy with a bolt of lightning.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lightningDamage: scaleUpFlat(level, 5, 6),
      lightningDamagePercent: scaleDownFlat(level, 6),
      airDamagePercent: scaleDownFlat(level, 2),
    }),
  },
  elementalMastery: {
    id: 'elementalMastery',
    name: () => 'Elemental Mastery',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[1],
    icon: () => 'elemental-mastery',
    description: () => 'Increases all elemental damage.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 0.75),
      elementalPenetration: scaleUpFlat(level, 8, 5),
      elementalPenetrationPercent: Math.min(scaleDownFlat(level, 0.1), 20),
    }),
  },

  // Tier 25 Skills
  blizzard: {
    id: 'blizzard',
    name: () => 'Blizzard',
    type: () => 'buff',
    manaCost: (level) => 10 + level * 1.25,
    cooldown: () => 88000,
    duration: () => 40000,
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'blizzard',
    description: () => 'Summons a blizzard, covering the battlefield in frost.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      coldDamagePercent: scaleDownFlat(level, 3),
      airDamagePercent: scaleDownFlat(level, 3),
      waterDamagePercent: scaleDownFlat(level, 3),
      lightningDamagePercent: scaleDownFlat(level, 3),
      coldDamage: scaleUpFlat(level, 3),
      airDamage: scaleUpFlat(level, 3),
      waterDamage: scaleUpFlat(level, 3),
      lightningDamage: scaleUpFlat(level, 3),
    }),
  },
  fireShield: {
    id: 'fireShield',
    name: () => 'Fire Shield',
    type: () => 'buff',
    manaCost: (level) => 20 + level * 0.5,
    cooldown: () => 37000,
    duration: () => 15000,
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'fire-shield',
    description: () => 'Surrounds the caster with a shield of fire. Deals only fire damage.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      reflectFireDamage: scaleUpFlat(level, 18),
      fireDamagePercent: scaleDownFlat(level, 2.5),
    }),
  },
  arcaneWisdom: {
    id: 'arcaneWisdom',
    name: () => 'Arcane Wisdom',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'wisdom',
    description: () => 'Increases mana and mana regeneration.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      manaPercent: scaleDownFlat(level, 1.5),
      manaRegen: scaleUpFlat(level, 0.2),
      manaRegenPercent: scaleDownFlat(level, 0.5),
      manaRegenOfTotalPercent: Math.min(scaleDownFlat(level, 0.005), 1),
    }),
  },

  // Tier 50 Skills
  elementalStorm: {
    id: 'elementalStorm',
    name: () => 'Elemental Storm',
    type: () => 'instant',
    manaCost: (level) => 50,
    cooldown: () => 4500,
    requiredLevel: () => SKILL_LEVEL_TIERS[3],
    icon: () => 'storm',
    description: () => 'Unleashes a storm of fire, ice, and lightning.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamage: scaleUpFlat(level, 2),
      elementalDamagePercent: scaleDownFlat(level),
    }),
  },
  elementalAffinity: {
    id: 'elementalAffinity',
    name: () => 'Elemental Affinity',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[3],
    icon: () => 'affinity',
    description: () => 'Increases resistance to elemental damage.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamage: scaleUpFlat(level, 1),
      elementalDamagePercent: scaleDownFlat(level, 0.5),
      intelligencePercent: scaleDownFlat(level, 0.75),
      allResistance: scaleUpFlat(level, 7),
    }),
  },

  // Tier 75 Skills
  arcanePulse: {
    id: 'arcanePulse',
    name: () => 'Arcane Pulse',
    type: () => 'buff',
    manaCost: (level) => 30 + level * 0.75,
    cooldown: () => 51000,
    duration: () => 25000,
    requiredLevel: () => SKILL_LEVEL_TIERS[4],
    icon: () => 'pulse',
    description: () => 'Increases attack rating and resource stealing.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      attackRatingPercent: scaleDownFlat(level, 1.9),
      lifePerHit: scaleUpFlat(level, 4),
      manaPerHit: scaleUpFlat(level, 0.5),
      attackSpeed: Math.min(scaleDownFlat(level, 0.0075), 1),
    }),
  },

  // Tier 100 Skills
  elementalOverload: {
    id: 'elementalOverload',
    name: () => 'Elemental Overload',
    type: () => 'toggle',
    manaCost: (level) => 4 + level * 0.625,
    requiredLevel: () => SKILL_LEVEL_TIERS[5],
    icon: () => 'overload',
    description: () => 'Boosts elemental damage.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 2),
      coldDamagePercent: scaleDownFlat(level, 2),
      airDamagePercent: scaleDownFlat(level, 2),
      lightningDamagePercent: scaleDownFlat(level, 2),
    }),
  },
  primordialControl: {
    id: 'primordialControl',
    name: () => 'Primordial Control',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[5],
    icon: () => 'control',
    description: () => 'Grants control over elemental forces, increasing all stats.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      earthDamagePercent: scaleDownFlat(level, 1.5),
      vitality: scaleUpFlat(level, 5),
      vitalityPercent: scaleDownFlat(level, 2),
      wisdomPercent: scaleDownFlat(level, 2),
    }),
  },

  // Tier 200 Skills
  avatarOfTheElements: {
    id: 'avatarOfTheElements',
    name: () => 'Avatar of the Elements',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[6],
    icon: () => 'avatar-of-elements',
    description: () => 'Transforms the caster into a being of pure elemental power.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 1.2),
      elementalDamage: scaleUpFlat(level, 3),
      allResistance: scaleUpFlat(level, 8, 5, 0.15),
      perseverance: scaleUpFlat(level, 5, 5),
      perseverancePercent: scaleDownFlat(level, 1.5),
    }),
  },

  // Tier 1200 Skills
  elementalCorrosion: {
    id: 'elementalCorrosion',
    name: () => 'Elemental Corrosion',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[7],
    icon: () => 'elemental-corrosion',
    description: () => 'Deepen your command of all elements.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 1.4),
      elementalPenetrationPercent: Math.min(scaleDownFlat(level, 0.1), 20),
      manaRegenPercent: scaleDownFlat(level, 2),
    }),
  },
  volcanicWrath: {
    id: 'volcanicWrath',
    name: () => 'Volcanic Wrath',
    type: () => 'instant',
    manaCost: (level) => 25 + level * 1.25,
    cooldown: () => 100000,
    requiredLevel: () => SKILL_LEVEL_TIERS[7],
    icon: () => 'volcanic-wrath',
    description: () => 'Erupts fiery explosions around enemies.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 4),
      damage: scaleUpFlat(level, 8, 4),
      fireDamage: scaleUpFlat(level, 6, 6, 0.15),
    }),
  },

  // Tier 2000 Skills
  tempestNova: {
    id: 'tempestNova',
    name: () => 'Tempest Nova',
    type: () => 'instant',
    manaCost: (level) => 35 + level * 1.25,
    cooldown: () => 40000,
    requiredLevel: () => SKILL_LEVEL_TIERS[8],
    icon: () => 'tempest-nova',
    description: () => 'Summons a massive storm of elemental energy.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lightningDamage: scaleUpFlat(level, 10, 4),
      lightningDamagePercent: scaleDownFlat(level, 4),
      coldDamage: scaleUpFlat(level, 10, 4),
      coldDamagePercent: scaleDownFlat(level, 4),
    }),
  },
  earthShatter: {
    id: 'earthShatter',
    name: () => 'Earth Shatter',
    type: () => 'instant',
    manaCost: (level) => 30 + level * 1.25,
    cooldown: () => 25000,
    requiredLevel: () => SKILL_LEVEL_TIERS[8],
    icon: () => 'earth-shatter',
    description: () => 'Cracks the earth dealing heavy damage.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      earthDamagePercent: scaleDownFlat(level, 4),
      damage: scaleUpFlat(level, 30, 4, 0.2),
      armorPenetrationPercent: Math.min(scaleDownFlat(level, 0.5), 60),
    }),
  },

  // Tier 3000 Skills
  tidalWave: {
    id: 'tidalWave',
    name: () => 'Tidal Wave',
    type: () => 'buff',
    manaCost: (level) => 40 + level * 1.25,
    cooldown: () => 70000,
    duration: () => 30000,
    requiredLevel: () => SKILL_LEVEL_TIERS[9],
    icon: () => 'tidal-wave',
    description: () => 'Unleash a giant wave washing away enemies.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      waterDamage: scaleUpFlat(level, 15, 5, 0.2),
      waterDamagePercent: scaleDownFlat(level, 5),
      reduceEnemyAttackSpeedPercent: Math.min(scaleDownFlat(level, 0.1), 15),
    }),
  },
  stormLord: {
    id: 'stormLord',
    name: () => 'Storm Lord',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[9],
    icon: () => 'storm-lord',
    description: () => 'Command storms with ease.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lightningDamagePercent: scaleDownFlat(level, 5),
      elementalDamage: scaleUpFlat(level, 1.4),
      manaPercent: scaleDownFlat(level, 1.5),
    }),
  },

  // Tier 5000 Skills
  elementalAscension: {
    id: 'elementalAscension',
    name: () => 'Elemental Ascension',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[10],
    icon: () => 'elemental-ascension',
    description: () => 'Transcend normal limits of elemental power.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 1.5),
      elementalPenetrationPercent: Math.min(scaleDownFlat(level, 0.1), 15),
      allResistance: scaleUpFlat(level, 16),
    }),
  },
  natureCataclysm: {
    id: 'natureCataclysm',
    name: () => 'Nature Cataclysm',
    type: () => 'instant',
    manaCost: (level) => 50 + level * 1.25,
    cooldown: () => 28000,
    requiredLevel: () => SKILL_LEVEL_TIERS[10],
    icon: () => 'nature-cataclysm',
    description: () => 'Unleashes catastrophic elemental forces.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 5),
      coldDamagePercent: scaleDownFlat(level, 5),
      lightningDamagePercent: scaleDownFlat(level, 5),
      elementalDamage: scaleUpFlat(level, 8, 4),
    }),
  },
};
