import { t } from '../../i18n.js';
import { DEFAULT_MAX_SKILL_LEVEL, SKILL_LEVEL_TIERS } from '../../skillTree.js';
import { scaleDownFlat, scaleUpFlat } from '../../common.js';

// Elementalist skills extracted from skills.js
export const ELEMENTALIST_SKILLS = {
  // Tier 1 Skills
  fireball: {
    id: 'fireball',
    name: () => t('Fireball'),
    type: () => 'instant',
    manaCost: (level) => 2 + level * 0.25,
    cooldown: () => 5200,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'fireball',
    description: () => t('Launches a fireball dealing increased fire damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamage: scaleUpFlat(level, 2, 6),
      fireDamagePercent: scaleDownFlat(level, 4),
    }),
  },
  frostArmor: {
    id: 'frostArmor',
    name: () => t('Frost Armor'),
    type: () => 'buff',
    manaCost: (level) => 6 + level * 1.25,
    cooldown: () => 34000,
    duration: () => 10000,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'frost-armor',
    description: () => t('Encases the caster in frost, boosting armor and cold damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      armor: scaleUpFlat(level, 4, 8),
      armorPercent: scaleDownFlat(level, 3),
      coldDamagePercent: scaleDownFlat(level, 2),
    }),
  },

  warmth: {
    id: 'warmth',
    name: () => t('Warmth'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'storm',
    description: () => t('Increases mana, mana regeneration, and wisdom'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      manaPercent: scaleDownFlat(level, 2),
      manaRegen: scaleUpFlat(level, 0.2),
      manaRegenPercent: scaleDownFlat(level, 0.8),
      wisdomPercent: scaleDownFlat(level, 0.5),
      wisdom: scaleUpFlat(level, 2),
    }),
  },

  // Tier 10 Skills
  lightningStrike: {
    id: 'lightningStrike',
    name: () => t('Lightning Strike'),
    type: () => 'instant',
    manaCost: (level) => 4 + level * 0.375,
    cooldown: () => 3000,
    requiredLevel: () => SKILL_LEVEL_TIERS[1],
    icon: () => 'lightning',
    description: () => t('Strikes an enemy with lightning, increasing lightning and air damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lightningDamage: scaleUpFlat(level, 5, 7),
      lightningDamagePercent: scaleDownFlat(level, 4),
      airDamagePercent: scaleDownFlat(level, 2),
    }),
  },
  elementalMastery: {
    id: 'elementalMastery',
    name: () => t('Elemental Mastery'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[1],
    icon: () => 'elemental-mastery',
    description: () => t('Increases elemental damage and penetration.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 0.75),
      elementalPenetration: scaleUpFlat(level, 8, 5),
      elementalPenetrationPercent: Math.min(scaleDownFlat(level, 0.1), 20),
    }),
  },

  // Tier 25 Skills
  blizzard: {
    id: 'blizzard',
    name: () => t('Blizzard'),
    type: () => 'buff',
    manaCost: (level) => 10 + level * 1.25,
    cooldown: () => 88000,
    duration: () => 40000,
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'blizzard',
    description: () => t('Summons a blizzard that boosts all elemental damages.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      coldDamagePercent: scaleDownFlat(level, 3),
      airDamagePercent: scaleDownFlat(level, 3),
      waterDamagePercent: scaleDownFlat(level, 3),
      lightningDamagePercent: scaleDownFlat(level, 3),
      coldDamage: scaleUpFlat(level, 3),
      airDamage: scaleUpFlat(level, 3),
      waterDamage: scaleUpFlat(level, 3),
      lightningDamage: scaleUpFlat(level, 3),
    }),
  },
  fireShield: {
    id: 'fireShield',
    name: () => t('Fire Shield'),
    type: () => 'buff',
    manaCost: (level) => 20 + level * 0.5,
    cooldown: () => 37000,
    duration: () => 15000,
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'fire-shield',
    description: () => t('Surrounds the caster with a fiery shield that reflects and increases fire damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      reflectFireDamage: scaleUpFlat(level, 18),
      fireDamagePercent: scaleDownFlat(level, 2.5),
    }),
  },
  arcaneWisdom: {
    id: 'arcaneWisdom',
    name: () => t('Arcane Wisdom'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'wisdom',
    description: () => t('Raises mana and various mana regeneration rates.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      manaPercent: scaleDownFlat(level, 1.5),
      manaRegen: scaleUpFlat(level, 0.2),
      manaRegenPercent: scaleDownFlat(level, 0.5),
      manaRegenOfTotalPercent: Math.min(scaleDownFlat(level, 0.005), 1),
    }),
  },

  // Tier 50 Skills
  elementalStorm: {
    id: 'elementalStorm',
    name: () => t('Elemental Storm'),
    type: () => 'instant',
    manaCost: (level) => 50,
    cooldown: () => 4500,
    requiredLevel: () => SKILL_LEVEL_TIERS[3],
    icon: () => 'storm',
    description: () => t('Unleashes a storm that adds elemental damage and damage percent.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamage: scaleUpFlat(level, 2),
      elementalDamagePercent: scaleDownFlat(level),
    }),
  },
  elementalAffinity: {
    id: 'elementalAffinity',
    name: () => t('Elemental Affinity'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[3],
    icon: () => 'affinity',
    description: () => t('Adds elemental damage, intelligence, and resistance.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamage: scaleUpFlat(level, 1),
      elementalDamagePercent: scaleDownFlat(level, 0.5),
      intelligencePercent: scaleDownFlat(level, 0.75),
      allResistance: scaleUpFlat(level, 7),
    }),
  },

  // Tier 75 Skills
  arcanePulse: {
    id: 'arcanePulse',
    name: () => t('Arcane Pulse'),
    type: () => 'buff',
    manaCost: (level) => 30 + level * 0.75,
    cooldown: () => 51000,
    duration: () => 25000,
    requiredLevel: () => SKILL_LEVEL_TIERS[4],
    icon: () => 'pulse',
    description: () => t('Boosts attack rating, life and mana per hit, and attack speed.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      attackRatingPercent: scaleDownFlat(level, 1.9),
      lifePerHit: scaleUpFlat(level, 4),
      manaPerHit: scaleUpFlat(level, 0.5),
      attackSpeed: Math.min(scaleDownFlat(level, 0.0075), 1),
    }),
  },

  // Tier 100 Skills
  elementalOverload: {
    id: 'elementalOverload',
    name: () => t('Elemental Overload'),
    type: () => 'toggle',
    manaCost: (level) => 4 + level * 0.625,
    requiredLevel: () => SKILL_LEVEL_TIERS[5],
    icon: () => 'overload',
    description: () => t('Boosts fire, cold, air, and lightning damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 2),
      coldDamagePercent: scaleDownFlat(level, 2),
      airDamagePercent: scaleDownFlat(level, 2),
      lightningDamagePercent: scaleDownFlat(level, 2),
    }),
  },
  primordialControl: {
    id: 'primordialControl',
    name: () => t('Primordial Control'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[5],
    icon: () => 'control',
    description: () => t('Increases earth damage, vitality, and wisdom.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      earthDamagePercent: scaleDownFlat(level, 1.5),
      vitality: scaleUpFlat(level, 5),
      vitalityPercent: scaleDownFlat(level, 2),
      wisdomPercent: scaleDownFlat(level, 2),
    }),
  },

  // Tier 200 Skills
  avatarOfTheElements: {
    id: 'avatarOfTheElements',
    name: () => t('Avatar of the Elements'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[6],
    icon: () => 'avatar-of-elements',
    description: () => t('Transforms the caster, boosting elemental damage, resistance, and perseverance.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 1.2),
      elementalDamage: scaleUpFlat(level, 3),
      allResistance: scaleUpFlat(level, 8, 5, 0.15),
      perseverance: scaleUpFlat(level, 5, 5),
      perseverancePercent: scaleDownFlat(level, 1.5),
    }),
  },

  // Tier 1200 Skills
  elementalCorrosion: {
    id: 'elementalCorrosion',
    name: () => t('Elemental Corrosion'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[7],
    icon: () => 'elemental-corrosion',
    description: () => t('Increases elemental damage, penetration, and mana regeneration.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 1.4),
      elementalPenetrationPercent: Math.min(scaleDownFlat(level, 0.1), 20),
      manaRegenPercent: scaleDownFlat(level, 2),
    }),
  },
  volcanicWrath: {
    id: 'volcanicWrath',
    name: () => t('Volcanic Wrath'),
    type: () => 'instant',
    manaCost: (level) => 25 + level * 1.25,
    cooldown: () => 100000,
    requiredLevel: () => SKILL_LEVEL_TIERS[7],
    icon: () => 'volcanic-wrath',
    description: () => t('Erupts fiery explosions with added fire and flat damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 4),
      damage: scaleUpFlat(level, 8, 4),
      fireDamage: scaleUpFlat(level, 6, 6, 0.15),
    }),
  },

  // Tier 2000 Skills
  tempestNova: {
    id: 'tempestNova',
    name: () => t('Tempest Nova'),
    type: () => 'instant',
    manaCost: (level) => 35 + level * 1.25,
    cooldown: () => 40000,
    requiredLevel: () => SKILL_LEVEL_TIERS[8],
    icon: () => 'tempest-nova',
    description: () => t('Summons a storm dealing heavy lightning and cold damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lightningDamage: scaleUpFlat(level, 10, 4),
      lightningDamagePercent: scaleDownFlat(level, 4),
      coldDamage: scaleUpFlat(level, 10, 4),
      coldDamagePercent: scaleDownFlat(level, 4),
    }),
  },
  earthShatter: {
    id: 'earthShatter',
    name: () => t('Earth Shatter'),
    type: () => 'instant',
    manaCost: (level) => 30 + level * 1.25,
    cooldown: () => 25000,
    requiredLevel: () => SKILL_LEVEL_TIERS[8],
    icon: () => 'earth-shatter',
    description: () => t('Cracks the earth, dealing earth damage and penetrating armor.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      earthDamagePercent: scaleDownFlat(level, 4),
      damage: scaleUpFlat(level, 30, 4, 0.2),
      armorPenetrationPercent: Math.min(scaleDownFlat(level, 0.5), 60),
    }),
  },

  // Tier 3000 Skills
  tidalWave: {
    id: 'tidalWave',
    name: () => t('Tidal Wave'),
    type: () => 'buff',
    manaCost: (level) => 40 + level * 1.25,
    cooldown: () => 70000,
    duration: () => 30000,
    requiredLevel: () => SKILL_LEVEL_TIERS[9],
    icon: () => 'tidal-wave',
    description: () => t('Unleashes a wave that deals water damage and slows enemy attacks.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      waterDamage: scaleUpFlat(level, 15, 5, 0.2),
      waterDamagePercent: scaleDownFlat(level, 5),
      reduceEnemyAttackSpeedPercent: Math.min(scaleDownFlat(level, 0.1), 15),
    }),
  },
  stormLord: {
    id: 'stormLord',
    name: () => t('Storm Lord'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[9],
    icon: () => 'storm-lord',
    description: () => t('Increases lightning and elemental damage while boosting mana.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lightningDamagePercent: scaleDownFlat(level, 5),
      elementalDamage: scaleUpFlat(level, 1.4),
      manaPercent: scaleDownFlat(level, 1.5),
    }),
  },

  // Tier 5000 Skills
  elementalAscension: {
    id: 'elementalAscension',
    name: () => t('Elemental Ascension'),
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[10],
    icon: () => 'elemental-ascension',
    description: () => t('Raises elemental damage, penetration, and resistance.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 1.5),
      elementalPenetrationPercent: Math.min(scaleDownFlat(level, 0.1), 15),
      allResistance: scaleUpFlat(level, 16),
    }),
  },
  natureCataclysm: {
    id: 'natureCataclysm',
    name: () => t('Nature Cataclysm'),
    type: () => 'instant',
    manaCost: (level) => 50 + level * 1.25,
    cooldown: () => 28000,
    requiredLevel: () => SKILL_LEVEL_TIERS[10],
    icon: () => 'nature-cataclysm',
    description: () => t('Unleashes catastrophic forces, boosting all elemental damage.'),
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 5),
      coldDamagePercent: scaleDownFlat(level, 5),
      lightningDamagePercent: scaleDownFlat(level, 5),
      elementalDamage: scaleUpFlat(level, 8, 4),
    }),
  },
};
