import { DEFAULT_MAX_SKILL_LEVEL, SKILL_LEVEL_TIERS } from '../../skillTree.js';
import { scaleDownFlat, scaleUpFlat } from '../../common.js';

// Paladin skills extracted from skills.js
export const PALADIN_SKILLS = {
  // Tier 1 Skills
  holyLight: {
    id: 'holyLight',
    name: () => 'Holy Light',
    type: () => 'instant',
    manaCost: (level) => 3 + level * 0.25,
    cooldown: () => 6000,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'light',
    description: () => 'A burst of holy light that heals allies and damages enemies. (max 5% of max life)',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      life: scaleUpFlat(level, 5, 5, 0.2),
      lifePercent: Math.min(scaleDownFlat(level, 0.065, 5, 50), 5),
    }),
  },
  smite: {
    id: 'smite',
    name: () => 'Smite',
    type: () => 'toggle',
    manaCost: (level) => 1,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'smite',
    description: () => 'A powerful strike that deals holy damage to enemies.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damage: scaleUpFlat(level, 1),
      damagePercent: scaleDownFlat(level),
      fireDamage: scaleUpFlat(level, 2),
      fireDamagePercent: scaleDownFlat(level, 2),
    }),
  },
  shieldBash: {
    id: 'shieldBash',
    name: () => 'Shield Bash',
    type: () => 'instant',
    manaCost: (level) => 3 + level * 0.125,
    cooldown: () => 4500,
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'bash',
    description: () => 'Bashes an enemy with your shield, stunning them.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damage: scaleUpFlat(level, 2),
      damagePercent: scaleDownFlat(level, 4),
    }),
  },
  divineProtection: {
    id: 'divineProtection',
    name: () => 'Divine Protection',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[0],
    icon: () => 'protection',
    description: () => 'Greatly increases armor and block chance.',
    maxLevel: () => 200,
    effect: (level) => ({
      armor: scaleUpFlat(level, 2),
      armorPercent: scaleDownFlat(level, 2),
      thornsDamage: scaleUpFlat(level, 1),
      thornsDamagePercent: scaleDownFlat(level, 0.5),
    }),
  },

  // Tier 10 Skills
  consecration: {
    id: 'consecration',
    name: () => 'Consecration',
    type: () => 'buff',
    manaCost: (level) => 12 + level * 0.75,
    cooldown: () => 70000,
    duration: () => 28000,
    requiredLevel: () => SKILL_LEVEL_TIERS[1],
    icon: () => 'consecration',
    description: () => 'Blesses the ground, dealing holy damage to enemies.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      fireDamagePercent: scaleDownFlat(level, 5),
      coldDamagePercent: scaleDownFlat(level, 5),
      lightningDamagePercent: scaleDownFlat(level, 5),
    }),
  },
  greaterHealing: {
    id: 'greaterHealing',
    name: () => 'Greater Healing',
    type: () => 'instant',
    manaCost: (level) => 8 + level * 0.375,
    cooldown: () => 18000,
    requiredLevel: () => SKILL_LEVEL_TIERS[1],
    icon: () => 'heal',
    description: () => 'Heals a large amount of life instantly.',
    maxLevel: () => Infinity,
    effect: (level) => ({
      life: scaleUpFlat(level, 8),
      lifePercent: Math.min(scaleDownFlat(level, 0.25), 20),
    }),
  },

  // Tier 25 Skills
  divineShield: {
    id: 'divineShield',
    name: () => 'Divine Shield',
    type: () => 'buff',
    manaCost: (level) => 13 + level * 0.625,
    cooldown: () => 47000,
    duration: () => 20000,
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'holy-shield',
    description: () => 'Creates a shield that absorbs damage.',
    maxLevel: () => 200,
    effect: (level) => ({
      armor: scaleUpFlat(level, 4),
      armorPercent: scaleDownFlat(level, 6),
      blockChance: Math.min(scaleDownFlat(level, 0.2), 25),
    }),
  },
  auraOfLight: {
    id: 'auraOfLight',
    name: () => 'Aura of Light',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[2],
    icon: () => 'holy-aura',
    description: () => 'Increases healing effects and reduces damage taken.',
    maxLevel: () => 500,
    effect: (level) => ({
      life: scaleUpFlat(level, 15),
      lifePercent: scaleDownFlat(level, 1.2),
      armorPercent: scaleDownFlat(level),
      allResistance: Math.min(scaleUpFlat(level, 0.25), 30),
    }),
  },

  // Tier 50 Skills
  wrathOfTheHeavens: {
    id: 'wrathOfTheHeavens',
    name: () => 'Wrath of the Heavens',
    type: () => 'instant',
    manaCost: (level) => 10 + level * 1,
    cooldown: () => 12400,
    requiredLevel: () => SKILL_LEVEL_TIERS[3],
    icon: () => 'wrath',
    description: () => 'Calls down holy energy to smite enemies.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damagePercent: scaleDownFlat(level, 2),
      lightningDamage: scaleUpFlat(level, 8),
      lightningDamagePercent: scaleDownFlat(level, 5),
      airDamagePercent: scaleDownFlat(level, 3),
    }),
  },
  beaconOfFaith: {
    id: 'beaconOfFaith',
    name: () => 'Beacon of Faith',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[3],
    icon: () => 'beacon',
    description: () => 'Increases healing done.',
    maxLevel: () => 500,
    effect: (level) => ({
      life: scaleUpFlat(level, 20),
      lifeRegenPercent: scaleDownFlat(level, 0.5),
      lifeRegenOfTotalPercent: Math.min(scaleDownFlat(level, 0.1), 1),
      extraDamageFromLifePercent: Math.min(scaleDownFlat(level, 0.02), 2.5),
    }),
  },

  // Tier 75 Skills
  holyBarrier: {
    id: 'holyBarrier',
    name: () => 'Holy Barrier',
    type: () => 'buff',
    manaCost: (level) => 30 + level * 0.875,
    cooldown: () => 44000,
    duration: () => 20000,
    requiredLevel: () => SKILL_LEVEL_TIERS[4],
    icon: () => 'barrier',
    description: () => 'Creates a holy barrier that increases all healing effects.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      vitality: scaleUpFlat(level, 4),
      vitalityPercent: scaleDownFlat(level, 0.5),
      resurrectionChance: Math.min(scaleDownFlat(level, 0.1), 20),
    }),
  },

  AidFromHeaven: {
    id: 'AidFromHeaven',
    name: () => 'Aid From Heaven',
    type: () => 'summon',
    summonStats: (level) => {
      return {
        percentOfPlayerDamage: Math.min(scaleDownFlat(level, 1), 120),
        damage: scaleUpFlat(level, 4),
        attackSpeed: Math.max(0.9, 0.7 + scaleDownFlat(level, 0.003)),
      };
    },
    manaCost: (level) => 20 + level * 0.875,
    cooldown: () => 66000,
    duration: () => 25000,
    requiredLevel: () => SKILL_LEVEL_TIERS[4],
    icon: () => 'aid-from-heaven',
    description: () => 'Summons an angel from the sky to aid allies.',
    maxLevel: () => 500,
    effect: (level) => ({}),
  },

  // Tier 100 Skills
  divineWrath: {
    id: 'divineWrath',
    name: () => 'Divine Wrath',
    type: () => 'toggle',
    manaCost: (level) => 4 + level * 0.3,
    requiredLevel: () => SKILL_LEVEL_TIERS[5],
    icon: () => 'wrath',
    description: () => 'Unleashes divine energy to increase damage and healing.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damagePercent: scaleDownFlat(level, 5),
      lifePerHit: scaleUpFlat(level, 2, 5, 0.2),
    }),
  },
  guardianAngel: {
    id: 'guardianAngel',
    name: () => 'Guardian Angel',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[5],
    icon: () => 'angel',
    description: () => 'Provides a chance to resurrect with maximum life upon death',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      attackSpeed: scaleDownFlat(level, 0.01),
      resurrectionChance: Math.min(scaleDownFlat(level, 0.1), 50),
      lifeRegen: scaleUpFlat(level, 2, 5, 0.2),
      lifeRegenPercent: scaleDownFlat(level, 0.5),
      allResistance: scaleUpFlat(level, 8),
    }),
  },

  // Tier 200 Skills
  ascension: {
    id: 'ascension',
    name: () => 'Ascension',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[6],
    icon: () => 'ascension',
    description: () => 'Grants significant bonuses to all attributes.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 0.75),
      endurance: scaleUpFlat(level, 3),
      endurancePercent: scaleDownFlat(level, 2),
      vitality: scaleUpFlat(level, 3),
      vitalityPercent: scaleDownFlat(level, 2),
      attackRatingPercent: scaleDownFlat(level, 3),
    }),
  },

  // Tier 1200 Skills
  celestialGuard: {
    id: 'celestialGuard',
    name: () => 'Celestial Guard',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[7],
    icon: () => 'celestial-guard',
    description: () => 'Greatly boosts block chance and armor.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      armorPercent: scaleDownFlat(level, 2),
      blockChance: Math.min(scaleDownFlat(level, 0.1), 25),
      lifeRegenPercent: scaleDownFlat(level),
    }),
  },
  holyCrusade: {
    id: 'holyCrusade',
    name: () => 'Holy Crusade',
    type: () => 'toggle',
    manaCost: (level) => 5 + level * 0.625,
    requiredLevel: () => SKILL_LEVEL_TIERS[7],
    icon: () => 'holy-crusade',
    description: () => 'Empowers attacks with holy power.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damagePercent: scaleDownFlat(level, 2),
      fireDamagePercent: scaleDownFlat(level, 3),
    }),
  },

  // Tier 2000 Skills
  radiantAegis: {
    id: 'radiantAegis',
    name: () => 'Radiant Aegis',
    type: () => 'buff',
    manaCost: (level) => 40 + level * 1.25,
    cooldown: () => 120000,
    duration: () => 40000,
    requiredLevel: () => SKILL_LEVEL_TIERS[8],
    icon: () => 'radiant-aegis',
    description: () => 'Forms a protective barrier of light.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      armor: scaleUpFlat(level, 15, 4, 0.1),
      allResistance: scaleUpFlat(level, 12.25, 4, 0.1),
      reflectFireDamage: scaleUpFlat(level, 30, 3, 1),
    }),
  },
  divineJudgment: {
    id: 'divineJudgment',
    name: () => 'Divine Judgment',
    type: () => 'instant',
    manaCost: (level) => 20 + level * 1,
    cooldown: () => 90000,
    requiredLevel: () => SKILL_LEVEL_TIERS[8],
    icon: () => 'divine-judgment',
    description: () => 'Calls down holy energy on foes.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damage: scaleUpFlat(level, 15),
      lightningDamagePercent: scaleDownFlat(level, 3),
      fireDamagePercent: scaleDownFlat(level, 3),
    }),
  },

  // Tier 3000 Skills
  angelicResurgence: {
    id: 'angelicResurgence',
    name: () => 'Angelic Resurgence',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[9],
    icon: () => 'angelic-resurgence',
    description: () => 'Chance to revive with greater strength.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      resurrectionChance: Math.min(scaleDownFlat(level, 0.1), 50),
      lifePercent: scaleDownFlat(level, 1.5),
      attackSpeed: scaleDownFlat(level, 0.01),
    }),
  },
  sacredGround: {
    id: 'sacredGround',
    name: () => 'Sacred Ground',
    type: () => 'buff',
    manaCost: (level) => 30 + level * 1.25,
    cooldown: () => 140000,
    duration: () => 45000,
    requiredLevel: () => SKILL_LEVEL_TIERS[9],
    icon: () => 'sacred-ground',
    description: () => 'Blesses the area, aiding allies.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      lifeRegen: scaleUpFlat(level, 5, 5, 1),
      lifeRegenPercent: scaleDownFlat(level, 1.5),
      manaRegenPercent: scaleDownFlat(level),
    }),
  },

  // Tier 5000 Skills
  eternalLight: {
    id: 'eternalLight',
    name: () => 'Eternal Light',
    type: () => 'passive',
    requiredLevel: () => SKILL_LEVEL_TIERS[10],
    icon: () => 'eternal-light',
    description: () => 'Radiates unwavering holy power.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      elementalDamagePercent: scaleDownFlat(level, 2),
      allResistance: scaleUpFlat(level, 15),
      lifePercent: scaleDownFlat(level, 2),
    }),
  },
  championOfFaith: {
    id: 'championOfFaith',
    name: () => 'Champion of Faith',
    type: () => 'toggle',
    manaCost: (level) => 10 + level * 1.25,
    requiredLevel: () => SKILL_LEVEL_TIERS[10],
    icon: () => 'champion-of-faith',
    description: () => 'Unleashes the ultimate holy might.',
    maxLevel: () => DEFAULT_MAX_SKILL_LEVEL,
    effect: (level) => ({
      damagePercent: scaleDownFlat(level, 3),
      fireDamagePercent: scaleDownFlat(level, 4),
    }),
  },
};
